### ISSUE TITLE
Not an issue, more of a request

### ISSUE THREAD

**Issue by reyco1** [CleverTap/clevertap-android-sdk#1]
Hi Guys,

We are an app development shop based out of Los Angeles, CA. I met with one of your representatives here in LA named Kara Drake and she was telling me about your services. To get to the point, we build hybrid apps using adobe air. We already have a few white label apps in the app store using other dashboards but we want to integrate CleverTap into them instead. After searching the internet, we could not find an AS3 SDK for your service. But I did come across your Java SDK. Is there any way that sdk could be open sourced so that we can create an AS3 version? We tried using the REST API independently, but there is no extensive documentation for that and we need to figure out how to specify that our api is coming from ios or android.

Is there anyway you guys could help us with that? Thank you in advanced!

Rey Columna
Founder, Appsfordable.com

**Comment by pwilkniss** [comment]
@reyco1  I've created the repo we discussed the other day.  let me know who I should invite thanks

**Comment by Xgamefactory** [comment]
you should support adobe air sdk
