### ISSUE TITLE
Sound notification not working on android 8 and above.

### ISSUE THREAD

**Issue by abhisheshsri** [CleverTap/clevertap-android-sdk#103]
I have added sound file in raw resources folder and followed all the steps mentioned in integration doc.I am able to see the notification but sound tune is not played above android version 8.
sdk version : 'com.clevertap.android:clevertap-android-sdk:3.8.1',

**Comment by darshanclevertap** [comment]
hi @abhisheshsri For Android 8 and above, you need to create the notification channel with your mentioned sound file. CleverTap SDK has provided a simple method for it. Please check the Step 4 in our documentation for [Creating Notification channels.](https://developer.clevertap.com/docs/android#section-push-notifications-for-android-o)
Also since you're here, I'd suggest you update to the latest CleverTap SDK version which is `v3.9.1` which has fixes related to Android 11 as well.

**Comment by abhisheshsri** [comment]
@darshanclevertap Tried with steps mentioned in step 4. Still not getting notification sound above android 8. 
You can easily reproduce the same in sample app by adding sound resource file in raw folder.

**Comment by darshanclevertap** [comment]
@abhisheshsri I think our support team has reached out to you and solved the issue for you. Closing this now.

**Comment by Divya015** [comment]
Hi Team,
I'm facing the same issue getting notifications but not the sound. We are using version 4.0.0. 
Please help.

**Comment by darshanclevertap** [comment]
@Divya015 Have you tried this?

> For Android 8 and above, you need to create the notification channel with your mentioned sound file. CleverTap SDK has provided a simple method for it. Please check the Step 4 in our documentation for [Creating Notification channels.](https://developer.clevertap.com/docs/android#section-push-notifications-for-android-o)

**Comment by Divya015** [comment]
@darshanclevertap 
Yes we are creating notification channel like below, which should get the default sound right? 

CleverTapAPI.createNotificationChannel(getApplicationContext(),"YourChannelId","Your Channel Name","Your Channel Description",NotificationManager.IMPORTANCE_MAX,true)

**Comment by shubhamS-vs** [comment]
@Divya015 I am facing the same issue. Have you found any solution to this?

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs Are you following this https://developer.clevertap.com/docs/add-a-sound-file-to-your-android-app

**Comment by shubhamS-vs** [comment]
> @shubhamS-vs Are you following this https://developer.clevertap.com/docs/add-a-sound-file-to-your-android-app

Yes i have tried this, not event default sound is coming, I am using clevertap-android-sdk:4.0.1

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs Can you try on real device once?

**Comment by shubhamS-vs** [comment]
> @shubhamS-vs Can you try on real device once?

Channel(
      'general',
      'General Channel',
      'This channel is for all general notifications.',
      1,
      true
    );
tried this also for default OS sound but still not working

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs It should work.

-  please try checking on real device
- check sound related settings on your phone. 
- check if channel created successfully in app settings
- check if channel is not silent

**Comment by shubhamS-vs** [comment]
@piyush-kukadiya can you help me that how can i check if channel is not silent and 
 channel created successfully in app settings?

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs https://support.google.com/android/answer/9079661?hl=en#zippy=

**Comment by shubhamS-vs** [comment]
@piyush-kukadiya Thank you

**Comment by BEGDAR8ZOUHAIR** [comment]
CleverTap.createNotificationChannelWithSound(
								"my_chanel",
								"my chanel ",
								"my chanel",
								5, 
								true,
								"sound.wav"
							);
still not work for me i use expo plugin for add sound to raw but not working custum sound ?
