### ISSUE TITLE
CTBackgroundJobService: java.lang.ClassNotFoundException in 4.0.0

### ISSUE THREAD

**Issue by nabil6391** [CleverTap/clevertap-android-sdk#115]
@darshanclevertap can you please have a look ? Its crashing like crazy in my app after updating to 4.0.0

`Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/base.apk", zip file "/data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.arm64_v8a.apk", zip file "/data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.en.apk", zip file "/data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/lib/arm64, /data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/base.apk!/lib/arm64-v8a, /data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.arm64_v8a.apk!/lib/arm64-v8a, /data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.en.apk!/lib/arm64-v8a, /data/app/com.photobook.android-NHcMybfimcy0XsFKIAXh1g==/split_config.xxhdpi.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
       at android.app.ActivityThread.handleCreateService(ActivityThread.java:4254)
       at android.app.ActivityThread.access$200(ActivityThread.java:242)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2083)
       at android.os.Handler.dispatchMessage(Handler.java:107)
       at android.os.Looper.loop(Looper.java:237)
       at android.app.ActivityThread.main(ActivityThread.java:7830)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1040)`

Thanks

**Comment by piyush-kukadiya** [comment]
@nabil6391 Did you check this https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md#-push-amplification-changes

**Comment by nabil6391** [comment]
You should have placed the changes in the Changelog.md as well:
https://github.com/CleverTap/clevertap-android-sdk/blob/master/CHANGELOG.md

Or in the releases tab
https://github.com/CleverTap/clevertap-android-sdk/releases

Anyways thanks for the prompt response. I am closing this now.
