### ISSUE TITLE
Inbox the item onclick

### ISSUE THREAD

**Issue by onesand** [CleverTap/clevertap-android-sdk#119]
Is there a callback for clicking on the inbox list? I know the link callback,but this not what i want.

**Comment by piyush-kukadiya** [comment]
@onesand Can you clarify in detail that what you want and what not.

**Comment by onesand** [comment]
When I click on an item in the inbox list, I want to receive a click callback. Is this possible?

**Comment by onesand** [comment]
I see ios has messageDidSelect

**Comment by piyush-kukadiya** [comment]
On Android we only have callbacks for inbox buttons and not for the inbox item. We will take it up internally but we cannot promise any timelines

**Comment by onesand** [comment]
Okay,Thank you!
