### ISSUE TITLE
NullPointerException on inboxlistener reference in ClevertapAPI class 

### ISSUE THREAD

**Issue by arora-vishal** [CleverTap/clevertap-android-sdk#134]
```
private void _notifyInboxMessagesDidUpdate() {
        if (this.inboxListener != null) {
            Utils.runOnUiThread(new Runnable() {
                @Override
                public void run() {
                    CleverTapAPI.this.inboxListener.inboxMessagesDidUpdate();
                }
            });
        }
    }
```
`_notifyInboxMessagesDidUpdate` is invoked on a worker thread and hence creates a race condition inside this method for inboxListener reference. Client can clear reference of inboxListener by `setCTNotificationInboxListener(null)` before the  `CleverTapAPI.this.inboxListener.inboxMessagesDidUpdate();` gets invoked on UI thread resulting in NPE on `CleverTapAPI.this.inboxListener` reference.

**Comment by darshanclevertap** [comment]
@arora-vishal This has been fixed in v4.0.1
