### ISSUE TITLE
Unable to render notification

### ISSUE THREAD

**Issue by sayagodshala** [CleverTap/clevertap-android-sdk#142]
Unable to render notification, channelId: Announcements and Updates not registered by the app.

Dependency 'com.clevertap.android:clevertap-android-sdk:4.0.0'

**Comment by darshanclevertap** [comment]
@sayagodshala Have you create a notification channel with the same name? As per the logs, SDK is unable to find the notification channel ID and hence cannot render the push notification

**Comment by sayagodshala** [comment]
Earlier it was working good, after updating the library from 3.7.2 to 4.0.0 somewhere something Is breaking. Like our custom instance of FirebaseMessagingService is not even getting triggered when notification is sent from CT dashboard but yes i can see logs.

Example : 
CleverTap:***-K5K-****: Handling notification: Bundle[{delivery_medium=CT, wzrk_acct_id=466-K5K-485Z, description=सद्गुरु से जाने ये खास बात!, notification_type=player, ct_notification=false, nm=🤔🧠दिमाग को अपने हिसाब से कैसे चलाएं?, nt=🤔🧠दिमाग को अपने हिसाब से कैसे चलाएं?, pr=, uri=app://kukufm/content-unit/%E0%A4%A6%E0%A4%BF%E0%A4%AE%E0%A4%BE%E0%A4%97-%E0%A4%95%E0%A5%8B-%E0%A4%85%E0%A4%AA%E0%A4%A8%E0%A5%87-%E0%A4%B9%E0%A4%BF%E0%A4%B8%E0%A4%BE%E0%A4%AC-%E0%A4%B8%E0%A5%87-%E0%A4%95%E0%A5%88%E0%A4%B8%E0%A5%87-%E0%A4%9A%E0%A4%B2%E0%A4%BE%E0%A4%8F%E0%A4%82-Dimag-ko-Apne-hisab-se-kaise-chalayen-sadhguru-Podcast, type=uri, image=https://kukufm.s3.ap-south-1.amazonaws.com/notification/Megha-onwards/Sadhguru.jpg, message=🤔🧠दिमाग को अपने हिसाब से कैसे चलाएं?, wzrk_pivot=wzrk_default, ct_campaign=allusers_2130, wzrk_cid=notification_podcast_channel, wzrk_nms=सद्गुरु से जाने ये खास बात!, wzrk_rnv=false, wzrk_ttl=1609847242, wzrk_push_amp=false, wzrk_bc=, wzrk_bi=2, wzrk_bp=https://kukufm.s3.ap-south-1.amazonaws.com/notification/Megha-onwards/Sadhguru.jpg, wzrk_dl=app://kukufm, wzrk_dt=FIREBASE, wzrk_id=0_0, wzrk_pn=true, wzrk_st=प्‍ले करने के लिए क्लिक करें}]

**Comment by darshanclevertap** [comment]
@sayagodshala CT SDK v4.0.0 was a major release. Please check if you have gone through all the changes [mentioned here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md)
Also if you could share some more logs, like what happens before and after you see the notification logs on the console, that would help.
Thanks!

**Comment by sayagodshala** [comment]
@darshanclevertap i think problem is with multiple instances of FirebaseMessagingService as there's two instances, one is our's and another is your's(**com.clevertap.android.sdk.pushnotification.fcm.FcmMessageListenerService**) and both services were listed in **androidmanifest.xml**  so I commented yours service and it worked as expected.

**Comment by darshanclevertap** [comment]
@sayagodshala Great! Closing this issue now 👍🏾
