### ISSUE TITLE
Clevertap 4.0.2. does allow to send push notification with customGcmSenderId

### ISSUE THREAD

**Issue by nabil6391** [CleverTap/clevertap-android-sdk#150]
After updating from 3.8.1 to 4.0.2, We are unable to send push notifications from our dashboard. 

The error that happens is our dashboard is this: 

**FCM Mismatch Sender ID**

The gcmSenderId in our manifest.xml and googleservices.json is different, but we own both the firebase projects. According to the clevertap documentation,  if we use the customSenderId in the manifest then the push notification should work. And it was working in previous version, now it is not working anymore.

Can you please have a look and suggest us what to do? We cannot change our gcmSenderId to the one in the googleservices.json because our production app already use the other gcmSenderId

**Comment by darshanclevertap** [comment]
@nabil6391 Can you check if the custom sender ID value in your `AndroidManifest.xml` and the value on the Push Settings in the CleverTap dashboard are the same?

Here is a screenshot to help you find Push Settings in the dashboard.

<img width="1219" alt="Screenshot 2021-01-29 at 3 28 12 PM" src="https://user-images.githubusercontent.com/29622446/106260631-9c08fe80-6246-11eb-9e0f-b44dff708d0e.png">

**Comment by nabil6391** [comment]
Hi @darshanclevertap , Yes I have verified that the custom sender ID and the one in the push settings in clevertap dashboard is the same.

**Comment by darshanclevertap** [comment]
@nabil6391 So the error "FCM Mismatch Sender ID" is because your FCM credentials of `google-services.json` in your app and the CleverTap dashboard are not the same. I'd suggest you raise a request to our Support Team via the Dashboard itself to get a faster solution.

**Comment by shubhamS-vs** [comment]
@darshanclevertap Do we have any option to trigger a notification from app? [React native]
Example , if user clicks on notify me button, can we send a scheduled notification to the user?
Any documentation for the same for react native app?
