### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by thirumal-r** [CleverTap/clevertap-android-sdk#166]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke interface method 'boolean pnb.e()' on a null object reference
android.os.Parcel.createExceptionOrNull (Parcel.java:2382)
com.android.installreferrer.api.InstallReferrerClientImpl.getInstallReferrer (InstallReferrerClientImpl.java:8)
com.clevertap.android.sdk.CleverTapAPI$35.onInstallReferrerSetupFinished (CleverTapAPI.java:5860)
com.android.installreferrer.api.InstallReferrerClientImpl$InstallReferrerServiceConnection.onServiceConnected (InstallReferrerClientImpl.java:5)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:967)

**Comment by darshanclevertap** [comment]
@thirumal-r Please share the following details - 

- Device: [e.g. OnePlus 9 Pro]
 - OS: [e.g. Android 10]
 - CleverTap SDK Version [e.g. v4.x.x]
 - Android Studio Version [e.g. v4.1.2]

**Comment by thirumal-r** [comment]
Find the details below,

Device: Redmi Note 9 Pro
OS: Android 10
CleverTap SDK Version 4.0.1
Android Studio Version 4.0.1

**Comment by darshanclevertap** [comment]
@thirumal-r Sorry for the delay, we'll try and reproduce this on our end and fix it in the next release

**Comment by william-ct** [comment]
Hi @thirumal-r , we have fixed the issue in the current version of the SDK(4.1.1).Do let us know if you are facing any other issues.Thanks!
