### ISSUE TITLE
Notification Small Icon Not Showing 

### ISSUE THREAD

**Issue by kartic-techindustan** [CleverTap/clevertap-android-sdk#167]
**Describe the bug**
In manifest, i have mentioned notification icon-
 
```
<meta-data
            android:name="CLEVERTAP_NOTIFICATION_ICON"
            android:value="@drawable/new_icon_push"/>
```

But, icon is not visible, gray square is visible only.
But if i create custom notification using NotificationCompat.Builder, its working fine.

 - Device: - Google Pixel 4A
 - OS: - Android 11
 - CleverTap SDK Version - 4.1.0
 - Android Studio Version - 4.1.3

**Comment by piyush-kukadiya** [comment]
@kartic-techindustan Please check **Warning** section here https://developer.clevertap.com/docs/android#section-set-the-small-notification-icon
