### ISSUE TITLE
Clevertap SDK v4.1.0 is crashing on Android SDK update to 30

### ISSUE THREAD

**Issue by athulantonynp** [CleverTap/clevertap-android-sdk#176]
CleverTap SDK v4.10 is crashing on several devices including Android 11 after updating to android targetSDKVersion to 30. Here is the log

`
Fatal Exception: java.lang.RuntimeException
Unable to create service com.clevertap.android.sdk.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/-880J9dHYZ527_jKHH2BKxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/me.ene-880J9dHYZ527_jKHH2BKxQ==/lib/arm64, /data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/me.e-880J9dHYZ527_jKHH2BKxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
Caused by java.lang.ClassNotFoundException
Didn't find class "com.clevertap.android.sdk.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/me.entri.entrime-880J9dHYZ527_jKHH2BKxQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/me.entri.entrime-880J9dHYZ527_jKHH2BKxQ==/lib/arm64, /data/app/~~Y9DzpM0BkAkz-GmXxAm7UQ==/me.entri.entrime-880J9dHYZ527_jKHH2BKxQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64, /product/lib64]]
`

**Comment by william-ct** [comment]
Hi @athulantonynp can you help us with the following information:-
Environment (please complete the following information):

Device: 
OS: 
CleverTap SDK Version: 
Android Studio Version:

Thanks
