### ISSUE TITLE
User Profiles getting merged with first logged in User

### ISSUE THREAD

**Issue by nishanth0299** [CleverTap/clevertap-android-sdk#177]
**Describe the bug**

On launching the android application very first time by logging in with user 1 the clevertap details for user1 is displayed as expected. Now on uninstalling the application and on reinstalling logged in with user 2, now the clevertap details for user 2 is getting merged with the user 1 profile 

**To Reproduce**

Scenario 1:(Login-Logout-Login)
1.Installed the app and Logged in with user1
2.On login we are calling onuserlogin
3.On landing on Dashboard page of the app we call pushprofile 
4.In clevertap an unique profile is created for user1
5.Logout from user1 - we are not calling any method on logout
6.  Login with user 2 and the same flow follows, we call onUserLogin 
7. We observe same behaviour as expected - (User1 and User2 has their own unique profiles in clevertap)

Scenario 2:(Login-Uninstall-Login)
1.Installed the app and Logged in with user1
2.On login we are calling onuserlogin
3.On landing on Dashboard page of the app we call pushprofile 
4.In clevertap an unique profile is created for user1
5.Uninstalled the app without Logging out for user 1
6. Reinstalled the app and Logged in with user 2 and the same flow follows, we call onUserLogin
7. Now in clevertap, the user2's profile is merged with user1's Profile
8. Again on Uninstalling without logging out user2 and reinstalled the app
9. Now logged in with user 3 and the same flow follows, we call onUserLogin
10. Now we observe the same - User3's profile is getting merged with user1's Profile

**Expected behavior**

On every user login after an Uninstall users must have unique CleverTap profiles, Instead of merging with the same profile/first logged in profile in the device

**Environment (please complete the following information):**

 - Device: OnePlus 7T
 - OS: Android 11
 - CleverTap SDK Version v3.9.1
 - Android Studio Version v3.5.3

**Comment by william-ct** [comment]
Hey @nishanth0299, during your login process are you using google_ad_id?

**Comment by nishanth0299** [comment]
No we don't have google_ad_id in our app and We've also created a ticket on
clevertap support  Ticket ID: SUC-82946

**Comment by darshanclevertap** [comment]
@nishanth0299 You are in great hands then. I'll be personally following the internal ticket as well and we'll step in if required. I'll keep this ticket open till your issue is resolved by our support team 👍🏾

**Comment by mehul7616** [comment]
I have faced this same issue id getting merged but not at uninstall when I uninstall the application or clear data from mobile and then after I log in so it's works properly creating a new profile and setting data but when I logout the user from the application and after logout i can log in so id getting merged logout code and login code is bellow mentioned 

logout:- 
    fun logoutUser() {

        lifecycleScope.launch {
            Currently.instance.onAppBackgrounded()
            preferenceDataStoreHelper?.clearAllPreference<T>()
            Currently.mSocketUtils?.disconnectSocket()
            Currently.mSocket?.disconnect()
        }

        SharedPrefsManager.clearPreference(this)
        val ai: ApplicationInfo = packageManager.getApplicationInfo(packageName, 0)

        val cacheDir = cacheDir
        val externalCacheDir = externalCacheDir
        cacheDir?.let { clearDirectory(it) }
        externalCacheDir?.let { clearDirectory(it) }

        // Clear data
        val dataDir = File(ai.dataDir)
        clearDirectory(dataDir)

        startIntentActivity<OnBoardingActivity<Any>>(true)
    }

    private fun clearDirectory(directory: File) {
        if (directory.exists()) {
            val files: Array<File>? = directory.listFiles()
            files?.let {
                for (file in it) {
                    if (file.isDirectory) {
                        clearDirectory(file)
                    } else {
                        file.delete()
                    }
                }
            }
        }
    }
    
    login ;- 
    
    val profileUpdate = HashMap<String, Any>()
                            profileUpdate["Identity"] =
                                loginData.second?.user?.phoneNumber.toString()
                            profileUpdate["Phone"] = viewModel?.etMobile?.get().toString().trim()
                            profileUpdate["Phone Number"] = ""
                            profileUpdate["Contact Permission"] = ""
                            profileUpdate["Notification Permission"] = ""
                            profileUpdate["Name"] = ""
                            profileUpdate["Email"] = ""
                            profileUpdate["User Id"] = ""
                            profileUpdate["@username"] = ""
                            profileUpdate["First Name"] = ""
                            profileUpdate["Last Name"] = ""
                            profileUpdate["Privacy"] = ""
                            profileUpdate["Gender"] = ""
                            profileUpdate["Date of Birth"] = ""
                            profileUpdate["User Bio"] = ""
                            profileUpdate["Photo"] = ""
                            profileUpdate["Nominated By"] = ""
                            profileUpdate["Followers"] = 0
                            profileUpdate["Following"] = 0
                            profileUpdate["Total Invites"] = 0
                            profileUpdate["Invites Pending"] = 0
                            profileUpdate["Nominated Count"] = 0
                            profileUpdate["MSG-email"] = false // Disable email notifications
                            profileUpdate["MSG-push"] = true // Enable push notifications
                            profileUpdate["MSG-sms"] = true // Disable SMS notifications
                            profileUpdate["MSG-whatsapp"] = true // Enable WhatsApp notifications
                            CleverTapAPI.getDefaultInstance(getBaseActivity())
                                ?.onUserLogin(profileUpdate)
