### ISSUE TITLE
Security Vulnerability in Clever-tap SDK 

### ISSUE THREAD

**Issue by anjalsaneen** [CleverTap/clevertap-android-sdk#180]
**Describe the bug**
According to the documentation of Clever tap, clients are enforce to add Api token in Manifest. it's a Very Vulnerable place to keep token. Anyone who reverse engineer APK can easily get these tokens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install apktool in your machine
2. decode any apk which has clevertap integrated
3. Open manifest file
4. See token in manifest 

**Expected behaviour**
If the Client can provide token programmatically, they can add extra layers of security on there needs

**Screenshots/Logs**
<img width="543" alt="Screenshot 2021-06-03 at 9 01 24 AM" src="https://user-images.githubusercontent.com/43947967/120582638-6bcaaa00-c44a-11eb-9bf4-2882ab5e9c40.png">

**Comment by darshanclevertap** [comment]
@anjalsaneen If you're using the native Android SDK, then we have an option of creating the instance of CleverTap without providing the Account ID and token in the `AndroidManifest.xml` file. You can read about it in our [Multi Instance SDK docs](https://developer.clevertap.com/docs/multi-instance-sdk-update). If you have any doubts or concerns or require any help in implementing this, you can reach out to our support team via the Dashboard and they'll be able to answer any questions for you.

**Comment by anjalsaneen** [comment]
Awesome. This works. You can close the ticket.
