### ISSUE TITLE
Security vulnerability issue

### ISSUE THREAD

**Issue by tallaltasawar** [CleverTap/clevertap-android-sdk#189]
I have used the CleverTap Android SDK and apparently the sdk used implicit pending intent which I found out after google sent me a security vulnerability report upon submitting my app to google play store, After analysing my codes and the all the third party utilities I was using I found out that this issue lies in the CleverTap SDK particularly in PushProvider class which uses PendingIntent extensively.

Google play store has suggested a remediation for this issue, I am posting the link in case it is helpful. 

[Suggested solution](https://support.google.com/faqs/answer/10437428)

**Comment by darshanclevertap** [comment]
@tallaltasawar We're seeing this issue with any of our clients for the first time. Could you please tell us which version of the CleverTap Android SDK are you using? 
Also, can you share the security vulnerability report sent to you by the Google Play Store?
If you're not comfortable sharing this information here, I'd suggest you raise a support issue via the CleverTap Dashboard and mention this Github issue and we'll take it up on priority.

**Comment by muhammad-rifais** [comment]
Hi @darshanclevertap 

We've got the same issue. Please refer to this https://support.google.com/faqs/answer/10437428

Thank you

**Comment by darshanclevertap** [comment]
@muhammad-rifais Can you please share the vulnerability report given by the Play Store with us? 

It will help us understand the issue better.

**Comment by tallaltasawar** [comment]
@darshanclevertap, I have already shared the steps to resolve the issue, but still you need the report it self I can only share a part of it due to NDA etc as it won't be of any help. 

Here it is.

<div class="pm-table-container  sc-emmjRN bTNvq" data-layout="default" style="font-style: normal; font-variant-caps: normal; font-weight: normal; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0px auto 16px; padding: 0px; position: relative; box-sizing: border-box; z-index: 0; transition: all 0.1s linear; display: flex; clear: both; caret-color: rgb(23, 43, 77); color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; font-size: 14px; white-space: pre-wrap; width: inherit;"><div class="pm-table-wrapper" style="margin: 0px; padding: 0px; overflow-x: auto;">

Vulnerability | APK Version(s) | Deadline to fix
-- | -- | --
Implicit PendingIntentYour app(s) contain an Implicit PendingIntent issue.To address this issue, follow the steps in this Google Help Center article. | XXXX | September XX, 20XX

</div></div><p data-renderer-start-pos="1437" style="font-style: normal; font-variant-caps: normal; font-weight: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; widows: auto; word-spacing: 0px; -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; margin: 0.75rem 0px 0px; padding: 0px; font-size: 14px; line-height: 1.714; letter-spacing: -0.005em; caret-color: rgb(23, 43, 77); color: rgb(23, 43, 77); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Roboto, Oxygen, Ubuntu, &quot;Fira Sans&quot;, &quot;Droid Sans&quot;, &quot;Helvetica Neue&quot;, sans-serif; white-space: pre-wrap;"> </p>

The solution suggested here has already been shared before by me and also by @muhammad-rifais here is the link 
https://support.google.com/faqs/answer/10437428

**Comment by darshanclevertap** [comment]
Closing this issue here as it is being tracked by our support team

**Comment by muhammad-rifais** [comment]
Hi @darshanclevertap when this issue can be rectified..? As this is blocking our app to roll-out.

Thank you
