### ISSUE TITLE
Enable JavaScript - In-app message

### ISSUE THREAD

**Issue by ghataa** [CleverTap/clevertap-android-sdk#19]
Hi guys,

I tried to use an In-app message with custom HTML + youtube video link, and get an error about "enable JavaScript..." (screenshot attached). Is there any option to enable js in that webview? Or any idea what should I do? Thanks!

<img width="942" alt="enable_js_clevertap_inapp" src="https://user-images.githubusercontent.com/26881582/54302699-b178cf00-45c1-11e9-88d2-5cb8b5a7eada.png">

**Comment by darshanclevertap** [comment]
Hi @ghataa 

Currently, we do not support Javascript inside our WebViews which are used to display Custom HTML InApps. This is currently being implemented as an enhancement and will be released in the next version of the CleverTap Android SDK (v3.4.3).
I'm marking this issue as an enhancement and will close it once we release the next version. 🙂

**Comment by darshanclevertap** [comment]
Hi @ghataa 
We have released this feature in our SDK v3.5.1, please check our official documentation on how to use Javascript in InApps. Closing this issue now.
