### ISSUE TITLE
Firebase multiple projects without google-services plugin not supported

### ISSUE THREAD

**Issue by shaz-tech** [CleverTap/clevertap-android-sdk#197]
We have configured multiple projects, hence not using the google-services.json file in our application instead of applying google-services we're loading the configuration from our server based on the variant.

There is no documentation from the Clevertap to configure with Firebase multiple projects without applying the google-services plugin.

**Working**: Events
**Not working**: Notification (As notification button is not showing in the profile after publishing the Firebase token to the dashboard)

**Link for reference**:
https://firebase.google.com/docs/projects/multiprojects

**Comment by william-ct** [comment]
Hi @shaz-tech , can you let us know which version of FCM and Clevertap's SDK are you using ?

**Comment by shaz-tech** [comment]
Clevertap version: 4.2.0
Firebase Bom Version: 24.0.2

**Comment by william-ct** [comment]
Hi @shaz-tech In your app's Manifest.xml file can you add the following:-
```
<meta-data
    android:name="FCM_SENDER_ID"
    android:value="@string/fcm_sender_id" />
```
While you're adding `fcm_sender_id` in `strings.xml`, append your sender_id after `id:` like below
`<string name="fcm_sender_id">id:fcm_sender_id</string>`

You can find your FCM sender id for the Firebase project [from here](https://developer.clevertap.com/docs/find-your-fcm-sender-id-fcm-server-api-key)

After adding the above can you confirm whether push notifications is working? Thanks!

**Comment by deb-anndy** [comment]
Hi @william-ct We are following the above solution but Mobile Push notification isn't subscribed for the user.

**Comment by william-ct** [comment]
Hey @deb-anndy Can you raise a support ticket of the issue via the CleverTap Dashboard and mention this Github issue and we'll take it up on priority. While raising the ticket can you also share an apk with us with `CleverTapAPI.setDebugLevel(3)`, so that we can debug it further. Thanks!
