### ISSUE TITLE
NullPointerException for isUsingTabs:  com.clevertap.android.sdk.CTInboxStyleConfig.isUsingTabs

### ISSUE THREAD

**Issue by nikhilk1993** [CleverTap/clevertap-android-sdk#198]
**Describe the bug**
Getting this clevertap crash for both android and ios in crashlytics

Unable to destroy activity {com.razorpay.payments.app/com.clevertap.android.sdk.inbox.CTInboxActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean com.clevertap.android.sdk.CTInboxStyleConfig.isUsingTabs()' on a null object reference

**stack trace**
android.app.ActivityThread.performDestroyActivity (ActivityThread.java:4383)
android.app.ActivityThread.handleDestroyActivity (ActivityThread.java:4401)
android.app.ActivityThread.-wrap5
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1649)
android.os.Handler.dispatchMessage (Handler.java:106)
android.os.Looper.loop (Looper.java:164)
android.app.ActivityThread.main (ActivityThread.java:6494)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:438)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:807)

**Screenshots/Logs**
<img width="1108" alt="Screenshot 2021-08-04 at 4 54 20 PM" src="https://user-images.githubusercontent.com/8143942/128172798-3f9646af-ca05-4a7f-8a98-82c04c5084e1.png">

**Environment (please complete the following information):**
 - Device: [Nexus 5s, iphone 10]

**Comment by darshanclevertap** [comment]
@nikhilk1993 we fixed a bunch of Strict Mode violations in our latest version v4.2.0
Can you check if this issue exists on our latest version as well?

**Comment by darshanclevertap** [comment]
Closing this for now. Please reopen this issue if you have any new inputs.
