### ISSUE TITLE
Getting ANR need some insight if reason is in SDK

### ISSUE THREAD

**Issue by niteshmunda** [CleverTap/clevertap-android-sdk#199]
**Describe the bug**
A possible ANR in SDK, has significant impact on performance

**To Reproduce**
No particular repro steps from app side, we have integrated ANR and got log in this.

**Expected behavior**
ANR should not happen. May be offloaded to different thread.

**Screenshots/Logs**
Attached screenshots.
<img width="1246" alt="Screenshot 2021-08-19 at 3 38 55 PM" src="https://user-images.githubusercontent.com/46442548/130051093-291caae6-df4e-4e51-b274-e5c4a49e246c.png">

**Environment (please complete the following information):**
 - Device: Not device specific. An example Galaxy M01
 - OS: 10
 - CleverTap SDK Version 4.0.0
 - Android Studio Version 4.2.2

**Additional context**
android.app.QueuedWork.addFinisher (QueuedWork.java:129)
**android.app.SharedPreferencesImpl$EditorImpl.apply (SharedPreferencesImpl.java:478)
com.clevertap.android.sdk.StorageHelper.persist (StorageHelper.java:38)
com.clevertap.android.sdk.StorageHelper.putInt (StorageHelper.java:153)
com.clevertap.android.sdk.CleverTapAPI.activityPaused (CleverTapAPI.java:4694)
com.clevertap.android.sdk.CleverTapAPI.onActivityPaused (CleverTapAPI.java:1045)**
com.clevertap.android.sdk.ActivityLifecycleCallback$1.onActivityPaused (ActivityLifecycleCallback.java:53)
android.app.Application.dispatchActivityPaused (Application.java:485)
android.app.Activity.dispatchActivityPaused (Activity.java:1331)
android.app.Activity.onPause (Activity.java:2259)
androidx.fragment.app.FragmentActivity.onPause (FragmentActivity.java:388)
**in.dunzo.errors.BaseMobiusActivity2.onPause (BaseMobiusActivity2.java:59)
in.dunzo.homepage.MainActivity.onPause (MainActivity.java:509)**
android.app.Activity.performPause (Activity.java:8142)
android.app.Instrumentation.callActivityOnPause (Instrumentation.java:1508)
android.app.ActivityThread.performPauseActivityIfNeeded (ActivityThread.java:4766)
android.app.ActivityThread.performPauseActivity (ActivityThread.java:4727)
android.app.ActivityThread.handlePauseActivity (ActivityThread.java:4679)
android.app.servertransaction.PauseActivityItem.execute (PauseActivityItem.java:46)
android.app.servertransaction.TransactionExecutor.executeLifecycleState (TransactionExecutor.java:176)
android.app.servertransaction.TransactionExecutor.execute (TransactionExecutor.java:97)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:2175)
android.os.Handler.dispatchMessage (Handler.java:107)
android.os.Looper.loop (Looper.java:237)
android.app.ActivityThread.main (ActivityThread.java:7857)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1068)

**Comment by darshanclevertap** [comment]
@niteshmunda This looks like some Read/Write issue related to Shared Preferences. We fixed a bunch of Read/Write`StrictMode` violations that flared up in our SDK after v4.0.0 in the latest release [v4.2.0](https://github.com/CleverTap/clevertap-android-sdk/releases/tag/core-v4.2.0) of the CleverTap Android SDK.
Could you please update to our latest SDK and let us know if the issue persists?

**Comment by darshanclevertap** [comment]
Closing this for now. Please reopen if you have any new inputs.
