### ISSUE TITLE
Security issues exposing unencrypted data

### ISSUE THREAD

**Issue by hartviqb** [CleverTap/clevertap-android-sdk#201]
Hi, 

We have an issue regarding the clevertap database in our android app which exposing our unencrypted user profile data, causing a high severity security issue based on the results of our independent penetration testers. is there any workaround to avoid that or how to encrypt that?

Thanks

![Screenshot 2021-09-28 145916](https://user-images.githubusercontent.com/8909820/135049696-2460d8be-bb1b-4bd1-9ab4-a201ad239971.png)

**Comment by hartviqb** [comment]
Hi @darshanclevertap could you help my problem?

**Comment by darshanclevertap** [comment]
Hi @hartviqb Sorry for the delay.

We do not encrypt and store the PII information as encryption and decryption would be a massive performance overhead for us. There are two types of encryption - local and server level. 

Local encryption would not be secure as we would have to use a public-private key at the SDK level and even after encryption, the public key would be exposed at the SDK level and hence would not solve the problem.

Server-level encryption would be to get the private key from the server and then encrypt the device-level information on the SDK. Currently, we do not have that capability, and even building such a capability would impact the real timeliness of the data which we send from the SDK as it would involve getting the keys from the server on the first App launch of the app on the device to encrypt the subsequent PII data which is shared with us.

If your company policies do not allow sending PII to us in an unencrypted format, the workaround is to pass PII data to us using our APIs. You can find the [API documentation](https://developer.clevertap.com/docs/api-overview) here.
