### ISSUE TITLE
Expected timeline with FCM v21.0.0 support?

### ISSUE THREAD

**Issue by inventionsbyhamid** [CleverTap/clevertap-android-sdk#212]
Is there any way we can switch to latest Firebase dependency and maintain compatibility with CleverTap? Is adding a direct dependency to `com.google.firebase:firebase-iid` a solution to use latest FCM version?

<img width="940" alt="image" src="https://user-images.githubusercontent.com/4223656/145369866-0cde62e0-9c2d-4e0c-9936-d5fe5026b615.png">

**Comment by darshanclevertap** [comment]
@inventionsbyhamid We're currently working on switching to the latest FCM dependency. We're looking to push out the next version of the CleverTap Android SDK with support for FCM v22 by the end of next week.

Adding a direct dependency of `com.google.firebase:firebase-iid` does not help if the app's FCM dependency is v21.0+
Hence directly switching to the latest FCM version is the only way forward.

**Comment by inventionsbyhamid** [comment]
Ok. Looking out for the release. Need to update the Firebase BOM on our end which has the latest FCM. Thanks!
