### ISSUE TITLE
Control on System events captured

### ISSUE THREAD

**Issue by manukj** [CleverTap/clevertap-android-sdk#214]
**Is your feature request related to a problem? Please describe.**
Right now the system events are captured automatically  when clevertap SDK is integrated, I went through the code and couldn't find a way to control the system events being captured 

**Describe the solution you'd like**
please let me know if we can control system events, if not please do add this feature

**Comment by darshanclevertap** [comment]
@manukj Can you please help us with the use case for controlling system events and which specific system events you'd like to control? We currently do not plan to have this specific feature in our roadmap but your use case would help us in triaging this issue internally.

**Comment by darshanclevertap** [comment]
@manukj Closing this issue for now. Feel free to reopen this once you can share your use case.
