### ISSUE TITLE
Ignoring Space and Upper/Lower Case

### ISSUE THREAD

**Issue by adesamp** [CleverTap/clevertap-android-sdk#216]
**Event property merged with 2 different name**
when I rename a event property, the new event is still increase in old event property

**To Reproduce**
1. you have event name A with event property `Abc Def`
2. trigger the event, then works well, the `Abc Def` event property in the dashboard is increase from 0 (nil) into 1
3. you rename it into `abcDef`
4. trigger the event again
5. then check to the dashboard, event `abcDef` is nothing, but `Abc Def` is increased into 2

**Expected behavior**
`abcDef` is increased into 1, but the `Abc Def` is still 1.

**Environment (please complete the following information):**
 - Device: Oppo F9
 - OS: Android 10
 - CleverTap SDK Version : 4.0.3
 - IntellijIdea 2021.3

**Additional context**
I debug it until the method processEvent, and the event property name is still valid.

![image](https://user-images.githubusercontent.com/61401530/146355989-bcb78b6e-fae0-4a60-96d2-0a7bd24ec935.png)

**Comment by root-ansh-ct** [comment]
Hi @adesamp . Thank you for reporting this issue. I have followed the steps and am able to reproduce this. We will take this with the backend team and get it fixed.

**Comment by darshanclevertap** [comment]
@adesamp We are working to fix this on the back end. I'm closing this issue now. I will provide an update once this is fixed.
