### ISSUE TITLE
Do we have any option to trigger a notification from app? [React native]

### ISSUE THREAD

**Issue by shubhamS-vs** [CleverTap/clevertap-android-sdk#219]
Example , if user clicks on notify me button, can we send a scheduled notification to the user?
Any documentation for the same for react native app?

**Comment by shubhamS-vs** [comment]
@darshanclevertap

**Comment by darshanclevertap** [comment]
@shubhamS-vs You can raise an event with the date/time user property and then create a campaign on the CleverTap dashboard for that particular date/time. There is no way to locally create/render push notifications for a given time.

To understand more on the date/time property, you can reach out to our support team with this query by raising a ticket via the CleverTap Dashboard.

**Comment by shubhamS-vs** [comment]
@darshanclevertap Can we record an event containing the date/time and then send notification to that user with that date/time?

**Comment by darshanclevertap** [comment]
@shubhamS-vs Yes you can raise an event with date/time as event property on the notify button and then create a Push Notification campaign on the CleverTap dashboard which will send out the push automatically.

**Comment by darshanclevertap** [comment]
@shubhamS-vs I hope your issue was solved. I'm closing this for now. Feel free to reopen if you have any more info.
