### ISSUE TITLE
FirebaseInstanceIdService is Deprecated

### ISSUE THREAD

**Issue by HaghighatDoost** [CleverTap/clevertap-android-sdk#22]
This class is deprecated and updating firebase library will cause an unresolved class error in AndroidManifest file here:
`<service
            android:name="com.clevertap.android.sdk.FcmTokenListenerService"
            android:exported="false">
            <intent-filter>
                <action android:name="com.google.firebase.INSTANCE_ID_EVENT" />
            </intent-filter>
        </service>`

FcmTokenListenerService is Overriding FirebaseInstanceIdService's onToeknRefresh() method

**Comment by darshanclevertap** [comment]
Hi @HaghighatDoost 

For now, we aren't supporting Firebase Messaging library v18.0.0. If you downgrade to Firebase Messaging v17.+ then CleverTap Android SDK will work smoothly. We are planning to support v18 soon.  I've marked this as an enhancement and incorporate it into our product roadmap. We will keep you updated.

**Comment by tancolo** [comment]
Hello @darshanclevertap 
So far, the Firebase message has been upgraded to 20.0.1. https://firebase.google.com/support/release-notes/android#messaging_v20-0-1
And I upgraded the version of Clevertap to 3.6.1, seems it also have this issue.

I think Clevertap should fix it ASAP.
Thank you.

Reference: 
1. https://firebase.google.com/docs/reference/android/com/google/firebase/iid/FirebaseInstanceIdService
2. https://medium.com/android-school/firebaseinstanceidservice-is-deprecated-50651f17a148

**Comment by darshanclevertap** [comment]
@tancolo @HaghighatDoost 
CleverTap Android SDK is still considering whether to upgrade our FCM dependencies to v18 and above as many of our users are still using the older dependencies. For now, if your app is using FCM v18 or above, please go through this [documentation](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above) which is a workaround
