### ISSUE TITLE
ANR on Clevertap

### ISSUE THREAD

**Issue by anjalsaneen** [CleverTap/clevertap-android-sdk#221]
**Describe the bug**
Getting ANR on clevertap

**Screenshots/Logs**
```
main (unknown)
tid=1 systid=11027
Triggered ANR
android.app.ContextImpl.getSharedPreferences (ContextImpl.java:479)
android.content.ContextWrapper.getSharedPreferences (ContextWrapper.java:199)
com.clevertap.android.sdk.StorageHelper.getPreferences (StorageHelper.java:18)
com.clevertap.android.sdk.StorageHelper.getPreferences (StorageHelper.java:22)
com.clevertap.android.sdk.StorageHelper.putInt (StorageHelper.java:159)
com.clevertap.android.sdk.ActivityLifeCycleManager.activityPaused (ActivityLifeCycleManager.java:67)
com.clevertap.android.sdk.CleverTapAPI.onActivityPaused (CleverTapAPI.java:847)
com.clevertap.android.sdk.ActivityLifecycleCallback$1.onActivityPaused (ActivityLifecycleCallback.java:53)
android.app.Application.dispatchActivityPaused (Application.java:468)
android.app.Activity.onPause (Activity.java:2439)
androidx.fragment.app.FragmentActivity.onPause (FragmentActivity.java:388)
android.app.Activity.performPause (Activity.java:8343)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1011)
```

**Environment (please complete the following information):**
 - Device: Any
 - OS: Any
 - CleverTap SDK Version 4.4.0
 - Android Studio Version Artic Fox

**Additional context**

Clevertap is creating its instance is on the main thread [here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/src/main/java/com/clevertap/android/sdk/CleverTapAPI.java#L861).

**Comment by root-ansh-ct** [comment]
Hi @anjalsaneen, can you share some steps to reproduce the above ANR?

**Comment by anjalsaneen** [comment]
Hi @root-ansh-ct 

We are not able to reproduce. These are traces from production App

**Comment by root-ansh-ct** [comment]
@anjalsaneen can you share any particular device's details on which the issue appeared? The following info will be useful: device android version, name, ram/storage info

**Comment by anjalsaneen** [comment]
<img width="349" alt="Screenshot 2022-02-08 at 12 01 14 PM" src="https://user-images.githubusercontent.com/43947967/152931080-da811881-d9fd-4f6d-8458-0140508a8aed.png">

Seems like it's happening across all manufacturers. some of the model's are

realme XT
V2022
vivo 1933
realme C15 Qualcomm Edition
Redmi Note 10S

**Comment by root-ansh-ct** [comment]
@anjalsaneen thanks for the info. we will investigate more on this
