### ISSUE TITLE
Inbox how disable exoplayer?

### ISSUE THREAD

**Issue by onesand** [CleverTap/clevertap-android-sdk#230]
Hi,If my project has the sdk of exoplayer, but we will not send audio and video messages, can I set the clevertap inbox not to use exoplayer?

**Comment by darshanclevertap** [comment]
@onesand I'm sorry, we do not have this configuration as of now. I'll take this up with my product team for consideration. For now, you can either use v2.11.5 of the ExoPlayer with CT Android SDK v4.0.0 - v4.2.0 or use ExoPlayer v2.15.1 with CT Android SDK v4.3.0 and above. 👍🏾

**Comment by JustinLim0318** [comment]
@onesand I able to disable the video support using 'Utils.haveVideoPlayerSupport = false' before open the app inbox

**Comment by onesand** [comment]
@darshanclevertap  I see, I'll keep trying to update the project SDK. Thanks again.

@JustinLim0318  I tried it, this works, thanks bro.
