### ISSUE TITLE
SDK has the Implicit PendingIntent Vulnerability

### ISSUE THREAD

**Issue by saczuac** [CleverTap/clevertap-android-sdk#232]
Please, be aware that the Android SDK has the Implicit PendingIntent Vulnerability:

<img width="953" alt="image" src="https://user-images.githubusercontent.com/20133363/155556782-e63a4e5e-5280-4921-9abd-99f3092b9672.png">

Could you fix this ?

Thanks in advance,

**Comment by piyush-kukadiya** [comment]
@saczuac Which SDK version are you using?

**Comment by saczuac** [comment]
"clevertap-react-native": "0.6.0", @piyush-kukadiya

**Comment by saczuac** [comment]
@piyush-kukadiya Do you think this issue can be resolved only updating the lib to 0.8.0 ?

**Comment by piyush-kukadiya** [comment]
@saczuac We added support for Android 12 in 0.7.0

**Comment by SiddhiBlackLotus** [comment]
<img width="980" alt="image" src="https://user-images.githubusercontent.com/79434215/155729840-ab3bd8c2-8bb1-411b-a8f8-5f7bd9a2de87.png">

I'm also getting the same error. Updating the SDK version to latest will resolve this error ?

**Comment by piyush-kukadiya** [comment]
@SiddhiBlackLotus We have added support for safe implicit pending intent for Android 12. clevertap-react-native v0.7.0 supports it. I would recommend please update to latest version.

**Comment by Priyanshi-Z** [comment]
Hi I am also facing same issue with android @piyush-kukadiya please suggest the solution. 
`
    implementation 'com.clevertap.android:clevertap-android-sdk:4.2.0' `

**Comment by Priyanshi-Z** [comment]
@piyush-kukadiya hi after updating the sdk to version 4.3.0 i have started getting an error in my project  :
` Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.13.`

**Comment by piyush-kukadiya** [comment]
@Priyanshi-Z Can you upload and share sample app showcasing your issue?

**Comment by piyush-kukadiya** [comment]
@Priyanshi-Z [Our sample app](https://github.com/CleverTap/clevertap-android-sdk/blob/master/sample/build.gradle#L46) is in working condition with latest SDK. We are using below versions in sample app, you can try them out.

`implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31"`
`distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-all.zip`

**Comment by Priyanshi-Z** [comment]
@piyush-kukadiya tried but it still doesn't works, can you suggest something else

**Comment by piyush-kukadiya** [comment]
@Priyanshi-Z Without sample app, can't help you. I would recommend, please raise a support ticket.

**Comment by Priyanshi-Z** [comment]
@piyush-kukadiya okay will be raising a ticket for it.  Just wanted to confirm once again we can still continue with our app releases. Our app release won't be impacted due to the above issue ?

**Comment by piyush-kukadiya** [comment]
@Priyanshi-Z Is this a build error or just a warning? Is your app working fine after this error?

**Comment by Priyanshi-Z** [comment]
@piyush-kukadiya 
I have got this error from play console

**Comment by piyush-kukadiya** [comment]
@Priyanshi-Z This error won't affect your app release as mentioned on [google page](https://support.google.com/faqs/answer/10437428)

> Fixing this issue is recommended but not mandatory. The publication status of your app will be unaffected by the presence of this issue. 

You can update your app to target Android 12 in future and this warning will go away. Right now you can safely release your app with Android 11. Hope this helps.

**Comment by piyush-kukadiya** [comment]
Feel free to reopen in case more help is needed
