### ISSUE TITLE
Android 12 support

### ISSUE THREAD

**Issue by Jparrgam** [CleverTap/clevertap-android-sdk#238]
**Describe the bug**
clevertap api support needed for android S+

**To Reproduce**
Run app with clevertap in device (Android 12)

**Environment (please complete the following information):**
 - Device: [e.g. OnePlus 9 Pro]
 - OS: Android 12
 - CleverTap SDK Version 4.0.4
 - Android Studio Dolphin | 2021.3.1 Canary 4

**Comment by piyush-kukadiya** [comment]
@Jparrgam Closing this for now. Feel free to reopen if any help required.
