### ISSUE TITLE
Disable Xiaomi push service on other manufacturers/devices

### ISSUE THREAD

**Issue by inventionsbyhamid** [CleverTap/clevertap-android-sdk#239]
We are seeing some ANRs on realme devices related to XMPushService. Is Xiaomi push service used to send push notifications by Clevertap on other devices as well? If yes how can we disable that to only be active on Xiaomi devices?

**Describe the solution you'd like**
Some way to disable Xiaomi push service on other manufacturers.

**Comment by piyush-kukadiya** [comment]
@inventionsbyhamid this is not possible right now, we will discuss this internally if we can provide this feature. You can try updating latest xiaomi sdk and see if it solves your issue.

**Comment by piyush-kukadiya** [comment]
Feel free to reopen in case more help is needed
