### ISSUE TITLE
React native createNotificationChannelWithSound importance

### ISSUE THREAD

**Issue by shubhamS-vs** [CleverTap/clevertap-android-sdk#240]
In react native i am passing 1 for importance in createNotificationChannelWithSound but still notification is going down in notification tray. @darshanclevertap

**Comment by root-ansh-ct** [comment]
Hi @shubhamS-vs  . To make Notifications with sound you need to provide an importance of minimum 3 to the channel.   checkout the various importance levels in the [chart given here ](https://developer.android.com/training/notify-user/channels#importance)
