### ISSUE TITLE
Any guide for push amplification for react native?

### ISSUE THREAD

**Issue by shubhamS-vs** [CleverTap/clevertap-android-sdk#241]
Any guide/documentation for push amplification for react native?

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs https://developer.clevertap.com/docs/android-push#push-amplification

**Comment by piyush-kukadiya** [comment]
Feel free to reopen in case more help is needed

**Comment by shubhamS-vs** [comment]
@piyush-kukadiya Can you please tell if i want to use push amplification just to keep resending the notification in case user has put his phone on DND , for that we just have to enable push amplification on dashboard or we also need to  the code changes as per the doc?

**Comment by piyush-kukadiya** [comment]
@shubhamS-vs Please reach out to our support team for any integration related queries.

**Comment by shubhamS-vs** [comment]
@piyush-kukadiya
here in the compatibility react native CT sdk is not mentioned
![Screenshot 2022-03-22 at 1 49 35 PM](https://user-images.githubusercontent.com/83690733/159448092-11ef640b-eb90-4e1d-bebe-5d27453e723c.png)
