### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to resume activity {our.company/com.clevertap.android.sdk.InAppNotificationActivity}: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.MaterialComponents (or a descendant).

### ISSUE THREAD

**Issue by mochadwi** [CleverTap/clevertap-android-sdk#255]
**Describe the bug**
Is there any version for `InAppActivity` to use `Theme.MaterialComponents`

**To Reproduce**
1. Crashed as explained in: https://github.com/pandulapeter/beagle/issues/99

**Expected behavior**
`InAppActivity` compatible with `Theme.MaterialComponents`

**Screenshots/Logs**

<img width="1099" alt="Screen Shot 2022-04-01 at 6 19 56 AM" src="https://user-images.githubusercontent.com/7057959/161165137-23b134c4-adae-4006-9ad8-a0ab82b71b3c.png">

**Environment (please complete the following information):**
 - Device: Redmi Note 7
 - OS: Android 10
 - CleverTap SDK Version v4.0.3
 - Android Studio Version
 
 Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+9-b1341.60 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.6
GC: G1 Young Generation, G1 Old Generation
Memory: 7168M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: com.github.lppedd.idea-conventional-commit (0.19.0), com.codestream.jetbrains-codestream (12.13.0+221), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)

**Additional context**

**Comment by mochadwi** [comment]
currently our apps pointing to material version `1.4.0-alpha01`, seems this will fix the issues, will update it later again after bumping and dogfooding :pray:

**Comment by root-ansh-ct** [comment]
closing this ticket due to inactivity. @mochadwi  hope the above mentioned solution worked for your product. feel free to open this ticket again if you face any issue 🙂
