### ISSUE TITLE
Isues in branch and CT integration

### ISSUE THREAD

**Issue by shubhamS-vs** [CleverTap/clevertap-android-sdk#258]
On branch dashboard in webhook section https://global.api.clevertap.com/branch? is giving 500 response when event is triggered from branch.
@piyush-kukadiya 
@darshanclevertap

**Comment by william-ct** [comment]
Hey @shubhamS-vs Need more info to debug this, I'd suggest you raise a support issue via the CleverTap Dashboard and mention this Github issue and we'll take it up on priority.

**Comment by shubhamS-vs** [comment]
@william-ct Done

**Comment by william-ct** [comment]
@shubhamS-vs We'll be tracking the support ticket that you've just raised, will close this issue here so that we can do any follow-up if required from the support ticket itself. Thanks 👍
