### ISSUE TITLE
In app feature is not working

### ISSUE THREAD

**Issue by kauhsikHundred** [CleverTap/clevertap-android-sdk#261]
**Describe the bug**
CleverTap "setInAppNotificationButtonListener" callback is not working or not able to access payload data for in app message feature. I passed the data in key pair value.

**Environment (please complete the following information):**
 - Device: Google play simulator 
 - OS: [e.g. Android 11]
 - CleverTap SDK Version [e.g. v4.4.0]
 - Android Studio Version [Android Studio Arctic Fox | 2020.3.1 Patch 3]

**Additional context**
Its working fine iOS not working in Android

**Comment by darshanclevertap** [comment]
@kauhsikHundred Apologies for the delay, are you still facing this issue? Could you provide the logs when the InApp button is clicked?
