### ISSUE TITLE
Support changing credentials for Xiaomi plugin at runtime

### ISSUE THREAD

**Issue by sriharshachilakapati** [CleverTap/clevertap-android-sdk#268]
**Is your feature request related to a problem? Please describe.**
We were using CleverTap SDK and Xiaomi SDK plugin along with it. Recently we undertook a change in our app where as an exercise part of security checks, we were moving all the API keys and credentials from the App to our Backend and get them when needed. We found `CleverTapAPI.changeCredentials` function to help with that, but similar change is not present in any place for Xiaomi SDK plugin.

**Describe the solution you'd like**
Just like we have `CleverTapAPI.changeCredentials` function, it would be helpful to have another function like `CleverTapAPI.changeXiaomiCredentials` which works for Xiaomi.

**Describe alternatives you've considered**
I've looked into the code, and seems this is implementable. However, we first raised it to support team, but this was closed unsatisfactorily by just pointing us to the docs instead, which again says to place the creds in manifest XML file as metadata. I wanted to raise a PR for the same, but wanted to run it through a discussion here, as you would be having more context than me.

**Additional context**
My understanding is that we can add two functions, one in `ManifestInfo` class and another in `CleverTapAPI` class. However, I'm not sure if any other places are needed. Since the `XiaomiSdkHandler` is using this `ManifestInfo` class directly, an override there, just like you were doing with `changeCredentials` would be sufficient.

**Comment by darshanclevertap** [comment]
Hi @sriharshachilakapati 

We understand your requirement and since we're open source, you can submit a PR for this. I will review it and we can incorporate your PR in the next release of the CleverTap Xiaomi SDK. 

But before you do submit the PR, I want to understand the priority on your end in terms of the timeline. We have certain tasks related to the CleverTap Xiaomi SDK which we will align with the next release as well.

**Comment by sriharshachilakapati** [comment]
@darshanclevertap We're planning on taking this as early as possible to release. By next week, we're moving all keys except for Xiaomi creds to backend. If it is possible on your end to release before that, it'd be pretty great. If not, I can defer just the Xiaomi creds for the next release, which is planned to be in next two weeks.

**Comment by darshanclevertap** [comment]
@sriharshachilakapati Yes, two weeks will be helpful. You can raise your PR this week and we will try to align the other changes around it. 👍🏾
