### ISSUE TITLE
InBox " Notification " Click Listener 

### ISSUE THREAD

**Issue by Abdohurbly** [CleverTap/clevertap-android-sdk#27]
Hello, 
I was trying to do some event on " InBox" Like Click Listener on one Promotion Notification.
but it's not there. 
is there any solution for this?

**Comment by darshanclevertap** [comment]
Hi @Abdohurbly 

Do you mean, you wanted to raise manually some events on the click of the button of an Inbox Notification?

**Comment by Abdohurbly** [comment]
@darshanclevertap Hello, 
yes exactly.
also if can  Click on inBox Notification itself. 
Note: implementation 'com.github.bumptech.glide:glide:4.9.0'//MANDATORY for App Inbox
this lib lead to crash the app on " inApp notification resived".

**Comment by darshanclevertap** [comment]
@Abdohurbly CleverTap raised a Notification Clicked event when any of the buttons of the Notification Inbox is clicked. You can check this on the dashboard for your user profile. We do not support custom events right now on the click of Inbox notifications.
Also for the issue of Glide dependency, can you tell me which version of the CleverTap SDK are you using currently and which version of the Glide dependency you are using in your app?

**Comment by Abdohurbly** [comment]
Hello Noted. 
about the lib, I'm using   -- cleverTap SDK:3.4.2' ||   glide:4.9.0'
Thanks.
Regards.

**Comment by darshanclevertap** [comment]
@Abdohurbly If you are using Glide v4.9.0, I would suggest you update CleverTap SDK to v3.5.1 as we have supported Glide v4.9.0 in our latest version.

**Comment by enofeb** [comment]
Do not you still have any support custom events  on the click of Inbox notifications?  @darshanclevertap

**Comment by darshanclevertap** [comment]
@enofeb We do not support custom events on the click on Inbox Notifications if you're using our InboxActivity.
If you want to raise custom events, you will have to create your own App Inbox using our [public methods mentioned here](https://developer.clevertap.com/docs/android#section-creating-your-own-app-inbox)
