### ISSUE TITLE
Null pointer issue 

### ISSUE THREAD

**Issue by nitin9096** [CleverTap/clevertap-android-sdk#28]
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'void com.clevertap.android.sdk.CleverTapAPI.b(java.lang.String, java.util.Map)'

Hi i am getting this issue . but nowhere from my side i am sending the Null a

**Comment by darshanclevertap** [comment]
@nitin9096 Can you tell me which version of the CleverTap Android SDK are you currently using and also share the stacktrace if any?

**Comment by nitin9096** [comment]
i am using **com.clevertap.android:clevertap-android-sdk:3.4.0** sdk version and .

i also tried sending null parameters in hashmap from my side intentionally in this case its not crashing. 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'void com.clevertap.android.sdk.CleverTapAPI.b(java.lang.String, java.util.Map)' on a null object reference
       at com.ayopop.analytics.clevertap.CleverTapTracker.pushEvent + 140(CleverTapTracker.java:140)
       at com.ayopop.analytics.clevertap.CleverTapTracker.onPromotionViewed + 572(CleverTapTracker.java:572)

**Comment by darshanclevertap** [comment]
@nitin9096 the line mentioned by you here `com.clevertap.android.sdk.CleverTapAPI.b` is being masked by your ProGuard and hence I cannot figure out which method is causing the issue. Can you please disable ProGuard on your debug build and send me a proper stack trace of the issue so that i can help you out better?

**Comment by darshanclevertap** [comment]
@nitin9096 Are you still facing this issue?
