### ISSUE TITLE
App Crashing on low device storage

### ISSUE THREAD

**Issue by arjun1194** [CleverTap/clevertap-android-sdk#287]
**Describe the bug**
App crashing on low device storage

**To Reproduce**
1. app storage low
2. Try to use Clever tap android sdk

**Expected behavior**
Error should be handled and crash should not occur event if the device storage is low
**Screenshots/Logs**
In case of crashes, share the entire crash logs as a `.txt` file
[crash.txt](https://github.com/CleverTap/clevertap-android-sdk/files/8959444/crash.txt)

**Environment (please complete the following information):**
 - Device: XT1663
 - OS: Android 6
 - CleverTap SDK Version  4.4.0
 - Android Studio Version 4.1.2

**Additional context**

**Comment by darshanclevertap** [comment]
@arjun1194 Are you still facing this issue? As per the logs, the crash is happening in the Room DB Library. CleverTap SDK does not use RoomDB for its Database.
