### ISSUE TITLE
onNotificationClickedPayloadReceived() does not work while the app is in background

### ISSUE THREAD

**Issue by jnlin** [CleverTap/clevertap-android-sdk#295]
**Describe the bug**
We implemented `onNotificationClickedPayloadReceived()` (source code attached below) however the onNotificationClickedPayloadReceived() was not executed while the app is in running in background. If the app was closed, onNotificationClickedPayloadReceived() was successfully called.

**To Reproduce**
1. Run the app, and switch to another app (to set the app running in background)
2. Send push notification via CleverTap
3. Click the push notification
4. It shows no logs in the logcat from Android Studio

**Expected behavior**
The function onNotificationClickedPayloadReceived() should be called 

**Screenshots/Logs**
```
class MainApp : Application(), CTPushNotificationListener {
  override fun onCreate() {
      if (!TextUtils.isEmpty(BuildConfig.cleverTapAccountId)) {
          ActivityLifecycleCallback.register(this)
      }
      CleverTapAPI.getDefaultInstance(applicationContext)?.let {
          it.ctPushNotificationListener = this@MainApp
      }
  }

  override fun onNotificationClickedPayloadReceived(payload: HashMap<String, Any>?) {
    d(payload.toString())
  }
}
```

**Environment (please complete the following information):**
 - Device: Pixel 5
 - OS: Android 12
 - CleverTap SDK Version: 4.5.1
 - Android Studio Version 
```
Android Studio Chipmunk | 2021.2.1
Build #AI-212.5712.43.2112.8512546, built on April 29, 2022
Runtime version: 11.0.12+0-b1504.28-7817840 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.4
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin (212-1.7.0-release-281-AS5457.46)
```

**Comment by mahima-zee** [comment]
I have a similar but different problem. I am unable to receive the callback when the app is closed and reopened on a notification action click. Did you get any solution to your problem? @jnlin 

I am registering the push notification listener as below in Activity's `onCreate`:

```
cleverTapAPI.setCTPushNotificationListener { payload ->
                    if (payload["actionId"]?.equals("ACTION_SHARE") == true) {
                        val shareText = payload["shareText"].toString()
                        openShareDialog(applicationContext, content = shareText)
                    }
            }
```

**Comment by jnlin** [comment]
@mahima-zee It's interesting. I moved my callback to MainActivity's `onCreate` but the callback only invoked while app is closed

**Comment by william-ct** [comment]
Hey @jnlin @mahima-zee, Please refer [CleverTap Developer Docs](https://developer.clevertap.com/docs/android-push#android-12-changes) for handling of ` onNotificationClickedPayloadReceived()` on  Android 12 devices

**Comment by jnlin** [comment]
Hi @william-ct, thank you for your help, it works :)
