### ISSUE TITLE
R8 warnings for clevertap 3.5.1

### ISSUE THREAD

**Issue by shivam-mygate** [CleverTap/clevertap-android-sdk#30]
While building obfuscated build, faced these warnings:

R8 WARNING:
Missing class: com.google.android.gms.iid.InstanceIDListenerService |  
Missing class: com.google.android.exoplayer2.Player$EventListener |  
Missing class: com.google.android.gms.gcm.GcmListenerService |  
Missing class: com.google.firebase.iid.FirebaseInstanceIdService |  

If I remove clevertap dependency from gradle, these warnings disappear.
Android studio version: 3.5

  compileSdkVersion 29
    buildToolsVersion '29.0.2'

   implementation 'com.google.firebase:firebase-analytics:17.1.0'
    implementation 'com.google.firebase:firebase-messaging:20.0.0'
    implementation 'com.google.firebase:firebase-database:19.0.0'
    implementation 'com.google.firebase:firebase-core:17.1.0'

  implementation 'com.clevertap.android:clevertap-android-sdk:3.5.1'

Please remove the warnings.

**Comment by darshanclevertap** [comment]
@shivam-mygate Can you help in elaborating the issue here? Do these warnings cause your app to not compile or build?

**Comment by shivam-mygate** [comment]
@darshanclevertap App compiles and builds successfully but R8 shows these warnings. It doesn't provide confidence that for every android version, device or manufacturer whether apk will work. Can it give ClassNotFoundException on certain conditions? 
Anyway, Clevertap should work towards removing these warning as way forward with compileSdkVersion 29

**Comment by darshanclevertap** [comment]
@shivam-mygate We will be moving our compileSdkVersion to 29 in the coming release. Approx ETA is 1st week of October. We are currently in the testing phase of the current release.

**Comment by shivam-mygate** [comment]
Thanks for the update.

**Comment by darshanclevertap** [comment]
@shivam-mygate We have fixed this in the CleverTap Android SDK v4.0.0. This is a major release so please check out the [changes here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) which we have made before updating.
