### ISSUE TITLE
Some components are not exported

### ISSUE THREAD

**Issue by KaustubhPatange** [CleverTap/clevertap-android-sdk#301]
Referencing lines https://github.com/CleverTap/clevertap-android-sdk/blob/master/clevertap-core/src/main/AndroidManifest.xml#L7-L15
```xml
<activity
    android:name="com.clevertap.android.sdk.InAppNotificationActivity"
    android:configChanges="keyboardHidden"
    android:theme="@android:style/Theme.Translucent.NoTitleBar" />

<activity
    android:name="com.clevertap.android.sdk.inbox.CTInboxActivity"
    android:configChanges="keyboardHidden"
    android:theme="@style/Theme.AppCompat.DayNight.DarkActionBar" />
```

Is there any reason why these components are not safely exported? It might cause issues with Android 12 devices when showing notifications.

**Comment by piyush-kukadiya** [comment]
@KaustubhPatange It doesn't have intent filter hence no need to specify. https://developer.android.com/about/versions/12/behavior-changes-12#exported

**Comment by KaustubhPatange** [comment]
Thanks for clearing up.
