### ISSUE TITLE
ConcurrentModificationException in clevertap sdk

### ISSUE THREAD

**Issue by shivam-mygate** [CleverTap/clevertap-android-sdk#31]
Crash in clevertap sdk:

Clevertap version: 3.4.2

Fatal Exception: java.util.ConcurrentModificationException
       at java.util.HashMap$HashIterator.nextNode + 1441(HashMap.java:1441)
       at java.util.HashMap$KeyIterator.next + 1465(HashMap.java:1465)
       at com.clevertap.android.sdk.CleverTapAPI.createNotification + 5132(CleverTapAPI.java:5132)
       at com.clevertap.android.sdk.CleverTapAPI.createNotification + 5105(CleverTapAPI.java:5105)

**Comment by darshanclevertap** [comment]
hi @shivam-mygate 

Can you help me out with a few things?

1. Do these crashes also occur in CleverTap Android SDK v3.5.1?
2. Steps to reproduce the above crashes.

This will help me out in figuring out the issue sooner and fixing them.

**Comment by shivam-mygate** [comment]
Hi @darshanclevertap 
Our current production app is on 3.4.2. In next release, we are going to update version to 3.5.1.
I don't know exact steps for reproducing this. It happened when we used clevertap campaign during weekend.

**Comment by darshanclevertap** [comment]
@shivam-mygate Can you share the campaign link?

**Comment by shivam-mygate** [comment]
Campaign id: 1567145359

**Comment by darshanclevertap** [comment]
@shivam-mygate It would help me if you could provide the link to me, if do not wish to share it here then you can write to us at support@clevertap.com and I'll look into it myself.

**Comment by darshanclevertap** [comment]
Closing this as it is being taken up by Support
