### ISSUE TITLE
[ANR] Service com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService

### ISSUE THREAD

**Issue by jeff-odopass** [CleverTap/clevertap-android-sdk#327]
**Describe the bug**
```
[libc.so] __ioctl
Executing service com.odopass.Odopass/com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService
```

This ANR is reported to my Google Play console. My app is written using Flutter, but basically it is just a wrapper around Android SDK.
I'm not able to reproduce myself the bug, which moreover happen in background (Probably when a push is received.)
100% from Android 11 SDK 30.
100% background.
Happened 50 times to 1 user.

I also have two variant ANR in the console which are exatcly the same except it is `java.io.UnixFileSystem.canonicalize0` and `android.os.MessageQueue.nativePollOnce` instead of `[libc.so] __ioctl`.

**Environment:**
 - Device: I don't have on Google Play for whatever reason
 - CleverTap Flutter plugin version: 1.5.1, Android SDK v4.4.0

**Additional context**
It does not looks like a big deal because it happens in background. However it probably should be fixed. I'm sorry I can't provide more trace or logs because I don't have it from the Play Console.

**Comment by piyush-kukadiya** [comment]
@jeff-odopass Can't you download trace from console or crashlytics? ANRs do have traces.

**Comment by piyush-kukadiya** [comment]
@jeff-odopass Can't find  `com.clevertap` in trace you attached.

**Comment by darshanclevertap** [comment]
@jeff-odopass Can you please share the screenshot of the Crashlytics dashboard if possible, it tells us which thread is the root cause of the ANR from this thread dump. Since none of these threads have CleverTap running, the root cause could be any of the following libs -

- Google Play Services Measurement
- Google Play Services Basement
- Firebase Installations
- Firebase Messaging

**Comment by jeff-odopass** [comment]
Hi @darshanclevertap, thanks for your feedback.
I checked again on my Google Play console and the problem did not occurred again since 1 month, it may have been solved by an update.
Because all the details I have has been posted in this thread and are not really relevant, and the error is no longer a problem for me, I think we can close this.
Have a nice day

**Comment by darshanclevertap** [comment]
Thanks @jeff-odopass 👍🏾
