### ISSUE TITLE
class file for com.clevertap.android.sdk.SyncListener not found

### ISSUE THREAD

**Issue by nathanielajayi7** [CleverTap/clevertap-android-sdk#363]
C:\Users\Nathan#\Desktop\luca-mobile\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java:29: error: cannot access SyncListener
      flutterEngine.getPlugins().add(new com.clevertap.clevertap_plugin.CleverTapPlugin());
                                ^
  class file for com.clevertap.android.sdk.SyncListener not found
1 error

Building for flutter with the recent v1.5.4 on pub.dev doesn't work

![Screenshot (37)](https://user-images.githubusercontent.com/54505255/203972802-a78de54e-18cc-46ab-87c9-b5229b12fa3c.png)

**Comment by shivamsharma2710** [comment]
Hi @nathanielajayi7 

How did you integrate the CleverTap plugin in your flutter project? Please mention all the setup related details.

**Comment by nathanielajayi7** [comment]
I added clever tap using

`flutter pub add clever_tap`

And followed the docs in the CleverTap Flutter SDK page

https://developer.clevertap.com/docs/flutter-sdk

**Comment by nathanielajayi7** [comment]
**** flutter pub add clevertap_plugin

**Comment by shivamsharma2710** [comment]
@nathanielajayi7 Have you added all the required **Gradle dependencies** correctly? 

Please, check this [link](https://developer.clevertap.com/docs/flutter-quick-start-guide#add-dependencies)

**Comment by nathanielajayi7** [comment]
This solves the problem. Thanks.
