### ISSUE TITLE
request: support of proxy domain for Android

### ISSUE THREAD

**Issue by DK070202** [CleverTap/clevertap-android-sdk#377]
Hi Clevertap Team,

I wanted to confirm if Android SDK supports a way to provide an option for a proxy domain on Android SDK, similar to [ios SDK](https://developer.clevertap.com/docs/ios-custom-proxy-domain) and [Web SDK](https://github.com/CleverTap/clevertap-web-sdk#add-your-clevertap-account-credentials) 

I was not able to find the option on docs, so wanted if there is a way to achieve this.

**Comment by darshanclevertap** [comment]
@DK070202 Currently we do not support proxy domain for Android. Please raise a support request via the CleverTap Dashboard and mention this GitHub issue and we'll ensure it reaches the correct team internally.

**Comment by darshanclevertap** [comment]
@DK070202 Closing this for now. As per my previous comment, please raise a support request via the CleverTap dashboard and mention this GitHub issue so that this request reaches the correct team
