### ISSUE TITLE
Migrate to androidx

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-android-sdk#38]
This sdk is still using the android support library, which is deprecated. Androidx has been out for quite a while now (over a year?). We'd like to remove jetifier from our app build process, but won't be able to until the sdks we use are on androidx.

**Comment by darshanclevertap** [comment]
Hi @calvarez-ov 

We are still using the Android support library because moving to AndroidX will cause a breaking change for apps who have not yet migrated to AndroidX. Jetifier helps apps migrated to AndroidX deal with non-AndroidX dependencies (like us). The vice versa is not possible. If jetifier works for you right now, I'd suggest holding on to it for a few more months.

Out of curiosity, out of all the SDKs used by your app, how many have migrated to AndroidX?

**Comment by calvarez-ov** [comment]
In our project, two sdks haven't migrated to androidx yet: CleverTap and MapBox.

**Comment by darshanclevertap** [comment]
@calvarez-ov I will mark this as an enhancement and take this up internally with my team but I cannot promise you any timelines for now. Hope you understand. Be that as it may, you will be the first to know when we are planning to migrate to AndroidX. Thanks!

**Comment by tonybarajas** [comment]
Hi, @darshanclevertap do you have some idea CleverTap can migrate to AndroidX. Because in my project I am using AndroidX and App inbox is not working it appears a message "Please upgrade com.android.support:design library to v28.0.0 to enable Tabs for App Inbox, dropping Tabs"

Thanks!

**Comment by darshanclevertap** [comment]
@tonybarajas We are still evaluating when to migrate to AndroidX. Meanwhile, for your App Inbox issue, I'd recommend adding the following two dependencies -

```
implementation 'androidx.legacy:legacy-support-v4:1.0.0'
implementation 'androidx.legacy:legacy-support-core-utils:1.0.0'

```    
Let me know if this works out for you!

**Comment by tonybarajas** [comment]
Hi @darshanclevertap I added the two dependencies and the logs just says the same:
Please upgrade com.android.support:design library to v28.0.0 to enable Tabs for App Inbox, dropping Tabs
**Note**: I am still using 
android.enableJetifier=true
android.useAndroidX=true

Do you know some workaround to be able to use App inbox with AndroidX?
Thanks!

**Comment by calvarez-ov** [comment]
In our project, now mapbox has migrated to androidx.

That makes CleverTap the only sdk in our app that still hasn't migrated to androidx.

**Comment by mochadwi** [comment]
Waiting for this, to be officialy supported. 

Meanwhile, I'm trying to host into internal private maven repository to change the actuals import package from support library to androidx instead, using `jetifier-standalone` from google

**Comment by calvarez-ov** [comment]
androidx has been stable for 1.5 years now. Can you please do the migration? Other projects who haven't migrated yet and are using CleverTap can continue to use the current 3.7.2 version of CleverTap.  If they haven't yet migrated to androidx, they're probably used to using legacy versions of libraries anyway 😛  The rest of us can continue to use recent stable versions (which have bug fixes).

**Comment by calvarez-ov** [comment]
Chet Haase from Google says “it’s time” to migrate to androidx:

https://youtu.be/2ov_23fTwyU?t=2m45s

At 2:45 in the video.

**Comment by mochadwi** [comment]
really agreed @calvarez-ov more and more recommendation from google for the apps and library developer to migrate into AndroidX, especially Android 11 and above, and they will stop the support library, really waiting for this to come officially :)

**Comment by mochadwi** [comment]
Since reading this closed #43 regarding firebase messaging, seems that a lot of clevertap functionality replaced such as FcmTokenListener and InAppNotification due to still using Support Library and firebase (below 19.x)

@calvarez-ov @darshanclevertap

**Comment by darshanclevertap** [comment]
@calvarez-ov @mochadwi We cannot migrate to AndroidX till there is some official announcement of the deprecation of the older support libraries as we have more than 8000 clients and developers using our SDK. Not all of them have moved to AndroidX and since the `jetifier` method is available for now as a workaround for people who have chosen to migrate.
Also @mochadwi your InAppNotificationActivity issue is something else and I've already replied on the other thread.

**Comment by calvarez-ov** [comment]
The message from Chet Haase saying the time is now, isn't enough?

**Comment by calvarez-ov** [comment]
The main page for the support library has a "DEPRECATED" watermark all over it: https://developer.android.com/topic/libraries/support-library :

![image](https://user-images.githubusercontent.com/9365138/80344954-ac7beb00-8868-11ea-89c7-c67bca2f369a.png)

It also says 
>We recommend using the AndroidX libraries in all new projects. You should also consider migrating existing projects to AndroidX as well.

**Comment by calvarez-ov** [comment]
Nick Anthony, Program Manager Android Jetpack, wrote an article a month ago saying "now is the time" to migrate to androidx: https://medium.com/androiddevelopers/migrating-to-androidx-tip-tricks-and-guidance-88d5de238876

Among the other reasons, the top one is:
>The Android Support Library has reached the end of its life. 28.0 was the last release of the Android Support namespace and the namespace is no longer maintained.

**Comment by hannesstruss** [comment]
@darshanclevertap out of curiosity, how many of your clients using the SDK have not yet migrated to AndroidX? I'd assume this number is pretty low, would it make sense for you to fork and freeze the CleverTap SDK for these clients, backporting only important security fixes and making life easier for the majority of your clients?

**Comment by mochadwi** [comment]
> @darshanclevertap out of curiosity, how many of your clients using the SDK have not yet migrated to AndroidX? I'd assume this number is pretty low, would it make sense for you to fork and freeze the CleverTap SDK for these clients, backporting only important security fixes and making life easier for the majority of your clients?

yes, backported for support library seems better (if there's bugfix) e.g in the latest supported AndroidX

**Comment by abhimaanmadhav** [comment]
@darshanclevertap still thinking of migration ? Being one our client we would strongly recommend you to migrate to androidX. if you have a few clients who are using support then maintain 2 sdk policy androidx,non androidx.

**Comment by darshanclevertap** [comment]
Hi guys, extremely sorry for the delay but I'm pleased to announce we have actively started working on the migration of our SDK to AndroidX support libraries. You can expect the AndroidX version to be out next month.

**Comment by darshanclevertap** [comment]
Hi guys,

We have brought AndroidX and Android 10 support in the CleverTap Android SDK v4.0.0. This is a major release so please check out the [changes here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) which we have made before updating.

**Comment by mochadwi** [comment]
Thanks a lot for this @darshanclevertap
