### ISSUE TITLE
Suggestion to change function default return value

### ISSUE THREAD

**Issue by temirnurdin** [CleverTap/clevertap-android-sdk#390]
**Describe the bug**
In the file CleverTapAPI.java, have these lines.
```
    /**
     * Checks whether notification permission is granted or denied for Android 13 and above devices.
     * @return boolean Returns true/false based on whether permission is granted or denied.
     */
    @SuppressLint("NewApi")
    public boolean isPushPermissionGranted(){
        if (isPackageAndOsTargetsAbove(context, 32)) {
            return coreState.getInAppController().isPushPermissionGranted();
        } else {
            return false;
        }
    }
```

**Expected behaviour**
Why it is returning `false` if the target is not above 32? 
Should not be returning true. 
I would expect that if the target is not above 32. Then it means no permission for pushes. So should return `true`.

**Comment by shivamsharma2710** [comment]
Hi @temirnurdin 

The method definition of `isPushPermissionGranted()` is intended. It's added for the Android 13 and above API levels to check the permission status. This is why it returns false if the first condition doesn't meet.  

Closing this ticket. Please feel free to open if you've any other query.
