### ISSUE TITLE
Can't change the fonts in promptPushPrimer Dialog

### ISSUE THREAD

**Issue by alkeshchamnani** [CleverTap/clevertap-android-sdk#391]
I cannot find any way to change the fonts for text in promptPushPrimer "InAppType.ALERT". As we are using custom font for our app we need to change the fonts for this dialog.

**Comment by darshanclevertap** [comment]
@alkeshchamnani Currently we do not support custom fonts since the Local InApp created is a part of the InApps feature of CleverTap. I'll take this up with our product team as a feature request.

**Comment by darshanclevertap** [comment]
@alkeshchamnani After discussing this internally, we do not plan on supporting custom fonts on the Push Primer in the near future.
