### ISSUE TITLE
[Clevertap][RenderMax] App getting crash on the Push Notifications

### ISSUE THREAD

**Issue by adeelcheetay** [CleverTap/clevertap-android-sdk#395]
**Describe the bug**
Since the integration of CleverTap RenderMax SDK we are receiving reports of crashes on Crashlytics `BroadcastReceiver$PendingResult.sendFinished`

**To Reproduce**
There are no steps available as it crashes on the end user devices, not every device. So we are unable to reproduce this on our testing devices.

**Expected behavior**
The app shouldn't crash due to RenderMax SDK

**Screenshots/Logs**
[clevertap_crash.txt](https://github.com/CleverTap/clevertap-android-sdk/files/10837282/clevertap_crash.txt)

**Environment (please complete the following information):**
 - Device: [Samsung, Xiaomi, Vivo, INFINIX MOBILITY LIMITEDHUAWEI,realme,OPPO,TECNO MOBILE LIMITED,INFINIX]
 - OS: [Android 11,12,10,9,8,13,7] in order of no. of crash reports
 - CleverTap SDK Version [v4.6.6] RenderMax: 1.0.2
 - Android Studio Version [Android Studio Electric Eel | 2022.1.1]

**Additional context**
N/A

**Comment by piyush-kukadiya** [comment]
@adeelcheetay We are aware of it and the fix will be available in next release.

**Comment by piyush-kukadiya** [comment]
@adeelcheetay Also for full confirmation please post entire stack trace of the crash

**Comment by adeelcheetay** [comment]
thanks, @piyush-kukadiya and this is the entire stack trace.

**Comment by piyush-kukadiya** [comment]
@adeelcheetay If you are using native SDK then we have released a fix for this https://github.com/CleverTap/clevertap-android-sdk/releases/tag/corev4.7.5_rmv1.0.3 
Please make sure to use RenderMax v1.0.3 and core v4.7.5 or else it will break the fix.

**Comment by adeelcheetay** [comment]
thanks @piyush-kukadiya

**Comment by adeelcheetay** [comment]
@piyush-kukadiya for the above issue, can we use the 4.6.8 version? with renderMax.

**Comment by piyush-kukadiya** [comment]
4.6.8 with renderMax version?

**Comment by adeelcheetay** [comment]
@piyush-kukadiya yes

**Comment by piyush-kukadiya** [comment]
@adeelcheetay Please avoid using RenderMax `v1.0.3` as issue still persists on this version. We are actively working towards possible solution.

**Comment by shiveshmehta2914** [comment]
is there any updates @piyush-kukadiya, as the crashing rates increasing day by day

**Comment by piyush-kukadiya** [comment]
Closing with a note.
Please check this out. https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTCORECHANGELOG.md#version-510-june-28-2023
The RenderMax Push SDK functionality is now directly supported within the CleverTap Core SDK. Consequently, the RenderMax SDK is deprecated. Please update the SDK to the latest version to avoid bugs and benefit from new features.
