### ISSUE TITLE
Large PNGs in SDK

### ISSUE THREAD

**Issue by aniketbhoite** [CleverTap/clevertap-android-sdk#40]
While analyzing the Increased size of APK I found these 3 Pngs which are on top by size.  
- ct_audio.png
- ct_image.png
- ct_video_1.png

I would like to know what is the purpose of these images they are just icons of approximately 1080x608. Why are they not in WebP or vector drawable. If they are used for notification icons then why are they so big. Using SDK v3.6.1. PFA 

![Screenshot 2019-11-26 at 3 25 00 PM](https://user-images.githubusercontent.com/13782400/69631515-0129f880-1074-11ea-89a6-4342908f5427.png)

**Comment by darshanclevertap** [comment]
@aniketbhoite Hi, thank you for pointing this out to us. We have been working at ways to reduce our AAR size as well and converting our PNGs to SVGs is first on our list. In our forthcoming releases, we will be removing unnecessary PNGs and converting the rest to a more optimized version of themselves.

**Comment by kumaratulismu** [comment]
@aniketbhoite Thanks for reporting this. We have replaced those with vector images. Will be released soon in the next version.
