### ISSUE TITLE
Didn't find class "com.clevertap.android.sdk.FcmTokenListenerService" crash on Coolpad devices

### ISSUE THREAD

**Issue by aniketbhoite** [CleverTap/clevertap-android-sdk#43]
Crash log
- Fatal Exception: java.lang.RuntimeException: Unable to instantiate service com.clevertap.android.sdk.FcmTokenListenerService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.FcmTokenListenerService" on path: DexPathList[[zip file "/data/app/app.babychakra.babychakra-1/base.apk"],nativeLibraryDirectories=[/data/app/app.babychakra.babychakra-1/lib/arm64, /vendor/lib64, /system/lib64]]
       at android.app.ActivityThread.handleCreateService + 3081(ActivityThread.java:3081)
       at android.app.ActivityThread.-wrap4(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage + 1594(ActivityThread.java:1594)
       at android.os.Handler.dispatchMessage + 111(Handler.java:111)
       at android.os.Looper.loop + 207(Looper.java:207)
       at android.app.ActivityThread.main + 5847(ActivityThread.java:5847)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run + 865(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main + 755(ZygoteInit.java:755)

Devices:- CoolPad
Os version:- 6.0
100% on Background
CleverTap SDK:- v3.6.1

**Comment by darshanclevertap** [comment]
@aniketbhoite Have you added the FCMTokenListenerService in your AndroidManifest.xml file?

**Comment by aniketbhoite** [comment]
Yes, we did.

**Comment by kumaratulismu** [comment]
@aniketbhoite Can you please share with us the version of firebase messaging, which you are using.

**Comment by aniketbhoite** [comment]
We use Firebase-messaging v20.0.0

**Comment by kumaratulismu** [comment]
@aniketbhoite  Thanks! for the information.

We are currently not supporting FCM V18 & above, and it's already in our release pipeline. Till the time we are coming out with a release we recommended you to use your own FirebaseMessaging service.

Please refer our [documentation](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above).

**Comment by aniketbhoite** [comment]
We do have our own class `MyFirebaseMessagingService` class extending `FirebaseMessagingService` class and all the steps are followed as mentioned in the [documentation  ](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above)

**Comment by darshanclevertap** [comment]
@aniketbhoite Since you have upgraded FCM to v20, please remove the FCMTokenListener class from your AndroidManifest.xml file to resolve this crash.

**Comment by aniketbhoite** [comment]
Will do that but can you explain why this issue occurs only on Coolpad devices?

**Comment by darshanclevertap** [comment]
@aniketbhoite This might happen on other devices as well. It depends on how Firebase gets initialized and authenticated during the runtime of the app.

**Comment by mochadwi** [comment]
> @aniketbhoite Thanks! for the information.
> 
> We are currently not supporting FCM V18 & above, and it's already in our release pipeline. Till the time we are coming out with a release we recommended you to use your own FirebaseMessaging service.
> 
> Please refer our [documentation](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above).

Is there any docs to configure `com.clevertap.android.sdk.InAppNotificationActivity` as well? when migrating to AndroidX, `InAppNotifiation` class still extends `com.clevertap.android.sdk.InAppNotificationActivity`

cc @darshanclevertap @kumaratulismu
