### ISSUE TITLE
Use new install referrer api (the current one will stop working in March 2020)

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-android-sdk#44]
The [documentation for referral tracking](https://developer.clevertap.com/docs/android#section-referral-tracking) refers to a broadcast receiver to track install referrers.

This mechanism will stop working in March 2020. We received this mail from Google Play:

> Hello Google Play Developer,
> 
> We recently [announced](https://android-developers.googleblog.com/2019/11/still-using-installbroadcast-switch-to.html) that we’ll be deprecating the install_referrer intent broadcast mechanism. Because one or more of your apps uses this intent to track referrals, we wanted to ensure you make the switch before **March 1, 2020**. After this date, new versions of the Play Store app will no longer broadcast the install_referrer intent after app installs.
> 
> Action required
> 
> [Migrate to the Play Install Referrer API](https://developer.android.com/google/play/installreferrer/library.html) to track your app installs for the following apps and/or games.
> 
> The Play Install Referrer API offers better performance, uses a secure communication channel between your app and the Play Store, and offers a more robust solution against spoof and attribution fraud.
> We know this change may require some additional work on your part and appreciate your understanding.

Could you please update the sdk to use the new install referrer apis, and update the documentation?

Thanks!

**Comment by darshanclevertap** [comment]
hi @calvarez-ov 

Thank you for bringing this to our notice. I will be taking this up on high priority with our Product team and will get back to you regarding by when we can do a release for this.

**Comment by darshanclevertap** [comment]
@calvarez-ov 
Update on this, we will be releasing a new SDK version in the second week of January which will have the changes regarding the new Install Referrer mechanism. Since the existing way will be deprecated, our code changes will not support backward compatibility and will only proceed with the new way of handling the Instal Referrer API.
I will circle back here once the release is done. Thanks!

**Comment by darshanclevertap** [comment]
@calvarez-ov CleverTap Android SDK v3.6.3 is live and fixes the issue. Currently, both ways (Broadcast Receiver & Install Referrer Libray) work but we have added a deprecation warning to the receiver which goes in the `AndroidManifest.xml` file. We will be removing the Broadcast Receiver once Google deprecates in March.

**Comment by darshanclevertap** [comment]
Closing this now. Thank you for your patience on this! 🙂
