### ISSUE TITLE
Need to add minimum compileSdkVersion for sdk version 5.1.0

### ISSUE THREAD

**Issue by jboxx** [CleverTap/clevertap-android-sdk#445]
**Is your feature request related to a problem? Please describe.**
need to increase compile sdk or excluding certain dependencies

**Describe the solution you'd like**
add detail documentation for migration or reason why should updates

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/CleverTap/clevertap-android-sdk/assets/3339451/62746a1f-ed8c-4209-8efd-4cae13215647)

**Comment by jboxx** [comment]
my alternative solution is to add this 
![image](https://github.com/CleverTap/clevertap-android-sdk/assets/3339451/cdf6f495-aeb0-49ae-8ab8-cf238e044ab8)

force to use client appcompat

**Comment by Anush-Shand** [comment]
@jboxx This is a possible hack too if it works for your use-case. But it is not recommended
