### ISSUE TITLE
CleverTap not support Custom Screen Attributes

### ISSUE THREAD

**Issue by mohitagarwal** [CleverTap/clevertap-android-sdk#45]
`CleverTapApi` Class has `recordScreen(String screenName)` method which doesn't send any custom screen attributes.
Can we have a method which sends custom attributes too?
If not, why?

**Comment by darshanclevertap** [comment]
@mohitagarwal Could you please define your use case here for tracking screen attributes?

**Comment by mohitagarwal** [comment]
Whenever a screen is loaded we also want to also track what were some of the properties of screen...
for eg. 
which a/b segment does the screen belong to
if a product screen was visited what was the product id
what was the source for entering the screen, basically last screen/deeplink

so that when funnelling we can get smart analysis filtering on these properties.

**Comment by darshanclevertap** [comment]
@mohitagarwal 
The use-cases you mentioned are not natural for screen attributes. 
E.g. 
- AB segment is a part of the property of the user (not the screen he visits).
- Product id is an attribute of the event the user triggers (not screen view)
- Before and after screens are funnels and flows analytics which should not be an attribute of the screen.

We support all these use-cases, in a different way. Screen event does not require attributes as there are associated events which have attributes. `recordScreen()` method is just to track the screen name.

**Comment by sagrawal31** [comment]
@darshanclevertap how can we use the recorded screen name in the CleverTap dashboard? I couldn't seem to find anything solid in the docs neither in the dashboard.
