### ISSUE TITLE
Build error : Missing Glide classes while taking release build

### ISSUE THREAD

**Issue by theapache64** [CleverTap/clevertap-android-sdk#456]
**Describe the bug**
 After I bumped my AGP version to `8.1.0` and Kotlin version to `1.9.0` am getting below error while taking a `release` build

```
Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in ../app/build/outputs/mapping/prodInRelease/missing_rules.txt.
```

Looking at the `missing_rules.txt` file, I can see that it's happening due to `Glide` files. 

```
# Please add these rules to your existing keep rules in order to suppress warnings.
# This is generated automatically by the Android Gradle plugin.
-dontwarn com.bumptech.glide.Glide
-dontwarn com.bumptech.glide.RequestBuilder
-dontwarn com.bumptech.glide.RequestManager
-dontwarn com.bumptech.glide.request.BaseRequestOptions
-dontwarn com.bumptech.glide.request.RequestOptions
-dontwarn com.bumptech.glide.request.target.ViewTarget
```

Since am not using Glide in my project, backtracking the classes points to cleverTap SDK's `CTSimpleMessageViewHolder` class. 

![image](https://github.com/CleverTap/clevertap-android-sdk/assets/9678279/1838b39b-ac74-48bc-9dd5-a2fcbfff7390)

**To Reproduce**
1. Create a project with cleverTap Android SDK - `5.2.0`
2. Try take a `release`  build (proguard enabled)

**Expected behavior**
- Build shouldn't fail

**Environment (please complete the following information):**
 - Device: [e.g. OnePlus 9 Pro] Build issue, hence not device specific
 - OS: [e.g. Android 10] Build issue, hence not Android specific
 - CleverTap SDK Version [e.g. v4.x.x] `5.2.0`
 - Android Studio Version [e.g. v4.1.2] `Android Studio Giraffe | 2022.3.1`

**Additional context**
- Build is not failing with AGP `7.4.2` (Kotlin `1.7.20`)

**Comment by theapache64** [comment]
@darshanclevertap @shivamsharma2710 Missed one info. `compileSdk` is `34`

**Comment by shivamsharma2710** [comment]
Hi @theapache64 


Unfortunately, we are not currently supporting `compileSdk` 34. The latest CleverTap Android SDK version, v5.2.0, only supports `compileSdk` 33.

Thanks for your understanding.

**Comment by theapache64** [comment]
Is this happening because of `compileSdk` 34? Can you please provide a workaround for this?

**Comment by theapache64** [comment]
@shivamsharma2710 gentle reminder

**Comment by theapache64** [comment]
@shivamsharma2710 Why glide is mentioned as a `compileOnly` dependency ?

**Comment by darshanclevertap** [comment]
@theapache64 We use Glide for displaying images & GIFs in our App Inbox feature. Since this feature is an optional feature, Glide is marked as a `compileOnly` dependency.

**Comment by Anush-Shand** [comment]
This issue has been fixed in the latest releases. Please upgrade to `com.clevertap.android:clevertap-android-sdk` v6.1.0 and `com.clevertap.android:clevertap-hms-sdk` v1.3.4 to resolve this issue
