### ISSUE TITLE
Timer template with "pt_big_img" not delivering to device

### ISSUE THREAD

**Issue by MahaleTushar** [CleverTap/clevertap-android-sdk#470]
**Description of  the bug**
The timer template with the "pt_big_img" value is not getting delivered on Android devices.

If we use a Timer template without an image it works fine.

**Environment **
 - CleverTap SDK Version [5.1.0]
 - cleverTapTemplateVersion [1.1.0]

**Additional context**
We are not receiving Timer image notifications on any Android device i.e. Android 13,11.

**Comment by darshanclevertap** [comment]
@tusr can you please share the screenshot of the key values you are passing to us and the screenshot of the push rendering on the device?

**Comment by tusr** [comment]
@darshanclevertap please find the attached screenshot of the key values we are passing.
<img width="965" alt="Screenshot 2023-09-08 at 11 01 32 AM" src="https://github.com/CleverTap/clevertap-android-sdk/assets/17288973/38c46638-1fb6-4e38-b335-62d71273b99e">


The push is not received on the test device, and no screenshot is available for the Timer notification with the image.
we have tried passing image URL of different sizes as well, but not working

**Comment by Anush-Shand** [comment]
@tusr The timer template with similar key-values is working on my device. Could you share the logs and also try the same template without the **pt_big_image** key-value

**Comment by MahaleTushar** [comment]
@Anush-Shand Thanks for your prompt response on the issue, we have found the cause of the issue.
the CTFcmMessageHandler().createNotification(getApplicationContext(), message) was not called on Caller's thread in onMessageReceive() of messaging service.
