### ISSUE TITLE
Upgrading play-services-ads requires ads.APPLICATION_ID to be declared in app manifest

### ISSUE THREAD

**Issue by KarandikarMihir** [CleverTap/clevertap-android-sdk#474]
We received a warning from google play store saying that we need to upgrade `com.google.android.gms:play-services-ads` to latest. The package is not used directly by our app but it's required by Clevertap android SDK. 

According to [their docs](https://developers.google.com/admob/android/quick-start#import_the_mobile_ads_sdk), we have to add this part to `AndroidManifest.xml`. But we don't use AdMobs or Ad Manager console. 

We're unsure how to proceed after this. Please advise.

```xml
<manifest>
  <application>
    <!-- Sample AdMob app ID: ca-app-pub-3940256099942544~3347511713 -->
    <meta-data
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-xxxxxxxxxxxxxxxx~yyyyyyyyyy"/>
  </application>
</manifest>
```

![E169B8EF-5D29-4BA7-ABC7-51D5D892849F](https://github.com/CleverTap/clevertap-android-sdk/assets/17466938/309f4d98-de3a-4132-bc10-128a0517eea7)

**Comment by piyush-kukadiya** [comment]
@KarandikarMihir `com.google.android.gms:play-services-ads` is only needed if you wish to use the Advertising ID for creating the CleverTap ID. 
If the app is not using the following in app's manifest,
```
<meta-data
    android:name="CLEVERTAP_USE_GOOGLE_AD_ID"
    android:value="1"/>
```
then app dont need to add the ads library.
this is mentioned in our docs also -> https://developer.clevertap.com/docs/android-quickstart-guide#add-your-clevertap-credentials-in-the-androidmanifestxml-file

**Comment by KarandikarMihir** [comment]
@piyush-kukadiya Thanks for the prompt response! We are using `CLEVERTAP_USE_GOOGLE_AD_ID` in the app manifest. Because the ID is used for internal analytics. But we never had AD_ID as part of the app manifest. What should we do in this case?

**Comment by piyush-kukadiya** [comment]
@KarandikarMihir  you need to add it in the manifest if you want to use or decide on not using Google AD ID at all. If you need further help then the suggestion is to reach out to our support team

**Comment by KarandikarMihir** [comment]
@piyush-kukadiya Thanks for the support. But we resolved this.

FYI - If you're using `play-services-ads` for any reason but do not use AdMobs or AdManager account. Just add the following meta tag to your AndroidManifest.xml. It's a dummy ID given by google.

```xml
        <meta-data
          android:name="com.google.android.gms.ads.APPLICATION_ID"
          android:value="ca-app-pub-3940256099942544~3347511713"/>
```
