### ISSUE TITLE
Email is merging instead of update

### ISSUE THREAD

**Issue by Pritomk** [CleverTap/clevertap-android-sdk#486]
When I update my mail with clevertap api using
            profileUpdate.put(CleverTapManager.EMAIL, email);
            profileUpdate.put(CleverTapManager.IDENTITY, UserInfo.getInstance(context).getCpCustomerId());
            clevertapDefaultInstance.pushProfile(profileUpdate);
this methods the mail is adding in client profile instead of updating. I want to update the mail what should I do?

**Comment by shivamsharma2710** [comment]
Hi @Pritomk 

**Email** is an identifier for us and hence we merge them in the user-profile instead of updating it. Please let me know if you need further assistance with this.

**Comment by Pritomk** [comment]
When user login the new clevertap anonymous id allocate to user with corresponding email. But when the user logged out and sign up with different email both the user got merge(Everything is happening without closing the app). So how can I allocate different user for different email.

**Comment by shivamsharma2710** [comment]
Hi @Pritomk 

Please, refer the [CleverTap documentation](https://developer.clevertap.com/docs/user-profiles-android) on how to manage user profiles.
