### ISSUE TITLE
Manual Carousel: Image sequence getting messed up for release build

### ISSUE THREAD

**Issue by Dhaval4Proximity** [CleverTap/clevertap-android-sdk#488]
**Describe the bug**
With Manual carousel template, I am facing a issue on signed release build, for debug build it works fine
Issue: Image sequence gets messed up; previous image shows up even after clicking next; this repeats for couple of times
**To Reproduce**
1. Generate signed build
2. Render a manual carousel template PN on this
3. Click next, keep clicking next

Issue is not device specific; although with Redmi devices frequency of issue is high compare to others
Here is the payload that I’m receiving in onMessageReceive()
`{
    pt_small_icon_clr=#2c698d,
    wzrk_acct_id=ABC-DEF-GHI, 
    pt_manual_carousel_type=default, 
    pt_msg_summary=Order fast!, 
    wzrk_acts=[], 
    pt_dl1=https://play.google.com/store/apps/details?id=com.application.zomato&hl=en-IN,
    pt_dl2=https://play.google.com/store/apps/details?id=in.swiggy.android&hl=en-IN,
    pt_dl3=https://play.google.com/store/search?q=blinkit&c=apps&hl=en-IN,     
    pt_dl4=https://play.google.com/store/apps/details?id=com.poncho.eatclub&hl=en-IN,
    pt_dl5=https://play.google.com/store/apps/details?id=com.ubercab.eats&hl=en-IN,    
    pt_msg=Pick what you would like, 
    pt_msg_clr=#2c698d, 
    pt_dark={"pt_bg":"#FFFFFF","pt_msg_clr":"#2c698d","pt_title_clr":"#2c698d"}, 
    pt_img1=https://www.directcom.com/images/300x200/home-phone.jpg, 
    pt_img2=https://www.directcom.com/images/300x200/internet.jpg, 
    pt_img3=https://www.directcom.com/images/300x200/home-phone-lying--down.jpg, 
    pt_img4=https://www.directcom.com/images/300x200/tv.jpg, 
    pt_img5=https://www.directcom.com/images/300x200/money.jpg, 
    pt_title_clr=#2c698d, 
    nm=Pick what you would like, 
    nt=THE WAIT IS ALMOST OVER!, 
    pt_bg=#FFFFFF, 
    pt_id=pt_manual_carousel, 
    pt_light={"pt_bg":"#FFFFFF","pt_msg_clr":"#2c698d","pt_title_clr":"#2c698d"}, 
    pt_title=THE WAIT IS ALMOST OVER!,
    wzrk_cid=general_channel_notifications, 
    wzrk_clr=#2c698d,
    wzrk_ttl=1697888811, 
    pt_subtitle=youll love it!, 
    wzrk_ck=3574, 
    wzrk_dl=deeplink://to-open-app, 
    wzrk_pn=true, 
    wzrk_st=youll love it!
}
`
**Expected behavior**
Image sequence should be maintained, can be critical for few use case

**Screenshots/Logs**

https://github.com/CleverTap/clevertap-android-sdk/assets/102023872/700c2f15-b3d6-4391-8b14-27a6cb99ec4f

**Environment (please complete the following information):**
 - Device: not specific, Happens more frequently on Redmi
 - OS: Android 12, android 13
 - CleverTap SDK Version : 5.2.0
 - CleverTap Push Template Version: 1.1.0

**Comment by Anush-Shand** [comment]
@Dhaval4Proximity Thanks for pointing this out. This issue has been identified and we plan to fix it in the next release. You can expect the same by Monday
