### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.clevertap.android.sdk.pushnotification.fcm.CTFirebaseMessagingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.RemoteMessage

### ISSUE THREAD

**Issue by HGaurav328** [CleverTap/clevertap-android-sdk#496]
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.clevertap.android.sdk.pushnotification.fcm.CTFirebaseMessagingReceiver: java.lang.ClassNotFoundException: Didn't find class "com.google.firebase.messaging.RemoteMessage" on path: DexPathList[[zip file "/data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/base.apk", zip file "/data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.armeabi_v7a.apk", zip file "/data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.en.apk", zip file "/data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.xhdpi.apk"],nativeLibraryDirectories=[/data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/lib/arm, /data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/base.apk!/lib/armeabi-v7a, /data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.armeabi_v7a.apk!/lib/armeabi-v7a, /data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.en.apk!/lib/armeabi-v7a, /data/app/com.viewlift.hoichoi-Hb0eh4JcbIpei0TYnaTaCg==/split_config.xhdpi.apk!/lib/armeabi-v7a, /system/lib, /system/product/lib]]
       at android.app.ActivityThread.handleReceiver(ActivityThread.java:3426)
       at android.app.ActivityThread.access$1200(ActivityThread.java:200)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1667)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:193)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858

**Comment by darshanclevertap** [comment]
@HGaurav328 Please mention the CleverTap Android SDK version you are using and the version of the Firebase Cloud Messaging

**Comment by HGaurav328** [comment]
CleverTap Android SDK: 5.2.0
we are not using Firebase Cloud Messaging for tv build. because push notification is not for android tv.  push notification only for mobile app.

this crash is coming on android tv.

**Comment by darshanclevertap** [comment]
@HGaurav328 even though Android TV does not support Push Notifications, can you add the FCM to your Android TV build because the CleverTap Android SDK requires it.

**Comment by HGaurav328** [comment]
ok thanks
