### ISSUE TITLE
Release Build failed with  proguard-android-optimize.txt

### ISSUE THREAD

**Issue by sushantoghosh** [CleverTap/clevertap-android-sdk#50]
gradle :

shrinkResources true
minifyEnabled true
proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

proguard rules:

#-dontoptimize
#-dontpreverify
-optimizationpasses 10

Build failed log:

14:59:33 Shrinking...
14:59:33 Printing usage to [/var/lib/jenkins/workspace/Android-Live/app/build/outputs/mapping/Live/release/usage.txt]...
14:59:39 Removing unused program classes and class elements...
14:59:39   Original number of program classes: 28846
14:59:39   Final number of program classes:    28703
14:59:39 Optimizing (pass 1/10)...
15:01:30 
15:01:30 Unexpected error while evaluating instruction:
15:01:30   Class       = [com/clevertap/android/sdk/GcmTokenListenerService]
15:01:30   Method      = [onTokenRefresh()V]
15:01:30   Instruction = [6] invokestatic #27
15:01:30   Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/clevertap/android/sdk/GcmTokenListenerService] (with 1 known super classes) and [com/clevertap/android/sdk/FcmTokenListenerService] (with 1 known super classes))
15:01:30 Unexpected error while performing partial evaluation:
15:01:30   Class       = [com/clevertap/android/sdk/GcmTokenListenerService]
15:01:30   Method      = [onTokenRefresh()V]
15:01:30   Exception   = [java.lang.IllegalArgumentException] (Can't find common super class of [com/clevertap/android/sdk/GcmTokenListenerService] (with 1 known super classes) and [com/clevertap/android/sdk/FcmTokenListenerService] (with 1 known super classes))
15:01:30 
15:01:30 > Task :app:transformClassesAndResourcesWithProguardForLiveRelease FAILED
15:01:30 
15:01:30 FAILURE: Build failed with an exception.
15:01:30 
15:01:30 * What went wrong:
15:01:30 Execution failed for task ':app:transformClassesAndResourcesWithProguardForLiveRelease'.
15:01:30 > java.io.IOException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Can't find common super class of [com/clevertap/android/sdk/GcmTokenListenerService] (with 1 known super classes) and [com/clevertap/android/sdk/FcmTokenListenerService] (with 1 known super classes)
15:01:30 
15:01:30 * Try:
15:01:30 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by darshanclevertap** [comment]
Hi @sushantoghosh 
Sorry for the delay in this reply
Which version of the CleverTap Android SDK are you using?

**Comment by sushantoghosh** [comment]
@darshanclevertap implementation 'com.clevertap.android:clevertap-android-sdk:3.4.2'

**Comment by darshanclevertap** [comment]
@sushantoghosh GCM as a service was deprecated by Google last year and GCMTokenListenerService is now deprecated as a part of our codebase. I would suggest you upgrade our library to v3.6.0 or above.
Let me know if the problem still persists.

**Comment by darshanclevertap** [comment]
@sushantoghosh Was this resolved for you?

**Comment by kumaratulismu** [comment]
Closing the issue due to inactivity
