### ISSUE TITLE
_createNotification method not contain the wzrk_pid

### ISSUE THREAD

**Issue by VictorTellez** [CleverTap/clevertap-android-sdk#51]
![Screenshot 2020-02-11 at 16 54 39](https://user-images.githubusercontent.com/5931981/74253308-33500b80-4cef-11ea-8c5c-3e6f27b27a6e.png)
In Android device when we want to show the notification the wzrk_pid is not coming. I was following  this example: [using fcm version 1800 and above](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above) and I was sending push notification from dashboard but I can't see the notification in the app because of the `wzrk_pid` is not coming.

**Comment by darshanclevertap** [comment]
Hi @VictorTellez 
Were you sending the Push Notification by creating a campaign or directly from the user's profile page on the CleverTap Dashboard?

**Comment by VictorTellez** [comment]
@darshanclevertap I have sent it from: Segments->Find people -> Find by Identity -> Profile -> Push notification. Also I'm using Android 9.

**Comment by darshanclevertap** [comment]
If you send a Push Notification via the above route you mentioned, we do not send the `wzrk_pid` key. This key will be present if you send out a Push Notification via our Campaigns.
We use this key to ensure that every push notification that reaches the device is unique. May I ask why are you concerned about this key?

**Comment by VictorTellez** [comment]
@darshanclevertap Because I used your createNotification method, and it didn’t show the notification.
So, I used our own method to create and show notification and used hard-coded key “nt” and “nm” to get title and message. Do you think this is because I use this way
`Segments->Find people -> Find by Identity -> Profile -> Push notification`?
The point about this key is that is the one who is check to show the notification when you use CleverTapAPI.createNotifiction.

**Comment by darshanclevertap** [comment]
> The point about this key is that is the one who is check to show the notification when you use
CleverTapAPI.createNotification().

The key to check whether the Push Notification is from CleverTap is `wzrk_pn` and not `wzrk_pid` i can see in the screenshot provided by you that `wzrk_pn` is being sent to you

**Comment by VictorTellez** [comment]
@darshanclevertap The check that is not working in CleverTapApi is this one:
```
if (extras.getString(Constants.WZRK_PUSH_ID) != null) 
static final String WZRK_PUSH_ID = "wzrk_pid";
```
This is why the notification is not shown.

**Comment by darshanclevertap** [comment]
@VictorTellez 
If you send out a Push Notification using `Segments -> Find people -> Find by Identity -> Profile -> Push notification` we don't send the `wzrk_pid` key. 
The `if` statement you have mentioned only checks for the key if present. If it is not present then it proceeds without stopping the flow. I think there is confusion over here regarding why a Push Notification is not showing up on your device. Why don't we take this up on a formal channel? Please write in to us at support@clevertap.com and someone from our support team can get on a call with you and help you with this. Please do mention this Github ticket when you mail to us so that we can take it on priority.

**Comment by darshanclevertap** [comment]
@VictorTellez Was this resolved from your side?

**Comment by kumaratulismu** [comment]
Closing the issue due to inactivity

**Comment by TVasundhra1** [comment]
Is it possible to get the campaign_name in campaign related push notification. 

Specifications:
Android Os 12
CleverTap SDK 4.4.0

Requirements:
Needed this for tracking purpose
