### ISSUE TITLE
How to active the discard event again

### ISSUE THREAD

**Issue by imrankhanluhar** [CleverTap/clevertap-android-sdk#52]
Hi , i want to re-enable the an event , which is discarded before some time due to some reason . but  now i want to see this event data for some analysis .please tell me how can i re-enable the event  . Please Help .

**Comment by darshanclevertap** [comment]
@imrankhanluhar We do not handle such requests. Please write an email to support@clevertap.com in detail with your Account ID and the event which you want to not be discarded and they will be the right people to help you with this. Thanks!
