### ISSUE TITLE
[ANR] CleverTap RenderMax SDK causes ANR

### ISSUE THREAD

**Issue by TrumpDony** [CleverTap/clevertap-android-sdk#546]
Describe the bug
We are receiving reports of ANR on Crashlytics 

To Reproduce
No steps are available as it's produced on the end user devices.

Expected behavior
The app shouldn't produce ANR during the push rendering.

Screenshots/Logs

> main (runnable):tid=1 systid=31750 
>        at java.lang.Integer.valueOf(Integer.java:1213)
>        at java.lang.reflect.Method.invoke(Native method)
>        at com.clevertap.android.pushsdk.unregisterForContextMenu.<clinit>(:3669)
>        at com.clevertap.android.pushsdk.registerForContextMenu.onReceive(:1)
>        at android.app.ActivityThread.handleReceiver(ActivityThread.java:4526)
>        at android.app.ActivityThread.access$1800(ActivityThread.java:273)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2191)
>        at com.didiglobal.booster.instrument.ActivityThreadCallback.handleMessage(ActivityThreadCallback.java:75)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loopOnce(Looper.java:241)
>        at android.os.Looper.loop(Looper.java:342)
>        at android.app.ActivityThread.main(ActivityThread.java:8143)
>        at java.lang.reflect.Method.invoke(Native method)
>        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:583)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1045)

Environment (please complete the following information):

Device: [Samsung, Xiaomi, Vivo, INFINIX MOBILITY LIMITEDHUAWEI, Google]
OS: [Android 12,11,13] **100% background** state
CleverTap SDK Version [v6.0.0] RenderMax: [1.0.3] Push Templates: [1.2.1] clevertap-xiaomi-sdk:[1.5.4]
Android Studio Version [Android Studio Hedgehog | 2023.1.1 Patch 2]

Additional context
N/A

**Comment by piyush-kukadiya** [comment]
@TrumpDony Please check this out. https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTCORECHANGELOG.md#version-510-june-28-2023
RenderMax Push SDK functionality is now supported directly within the CleverTap Core SDK. RenderMax SDK is deprecated.

**Comment by TrumpDony** [comment]
Thanks a lot @piyush-kukadiya ,  i will remove RenderMax SDK.
