### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException Unable to create service com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService: java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by aaditya-doshi-hztl** [CleverTap/clevertap-android-sdk#576]
Using the 6.1.0 version for SDK and upon releasing the app to prod started getting this crash event in Firebase Crashlytics heavily. Any probable cause as to why it would happen ? Would be helpful if you can let me know the same and any solution to overcome the same. TIA

Stack trace from Crashlytics
Fatal Exception: java.lang.RuntimeException
Unable to create service com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/~~nxBt_oG34Qurxx3T2023kg==/com.enbd.android-4SzoOZ7yindg5qvrhANC2A==/base.apk", zip file

**Comment by Anush-Shand** [comment]
This crash is due to the pushamplification feature edge case  - where the user updates the app (clevertap-version v6.0.0 or below to v6.1.1) but doesn't launch the app within the pingFrequency time (4 hours by default)

This crash is once per user.

This crash is in the background (app functionality is not affected but user will see an alert that the app stopped)

Workaround until the fix is released is to disable the service by adding this to their AndroidManifest.xml

  <service
      android:name="com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService"
      android:exported="false"
      android:enabled="false"
      tools:ignore="MissingClass"/>
      
The above code may show an error but shouldn’t cause any problem

@aaditya-doshi-hztl

**Comment by aaditya-doshi-hztl** [comment]
@Anush-Shand Hey man, thanks for the prompt response. This helps, apart from doing this, would upgrading the SDK to latest would be a good idea ? and in the process of doing so would there be any special changes required to be done on the proguard rules or should that be taken care off itself by the SDK ?

**Comment by Anush-Shand** [comment]
@aaditya-doshi-hztl There was a critical bug identified in `6.1.0` and hence we recommend updating to v6.1.1.
Also make sure to add the above mentioned entry in the AndroidManifest file.
Other than this no other specific change is required.
Once the fix is deployed it will be great if you can confirm that all the crashes related to the above mentioned Exception go away

**Comment by aaditya-doshi-hztl** [comment]
@Anush-Shand Noted ! If possible, please keep this bug open until I post an update for the behavior after SDK update.

**Comment by Lakshyasukhralia** [comment]
@Anush-Shand  Any update about the anticipated release date for the updated SDK with the necessary fixes? Critical issues were identified in version 6.0.0, prompting an urgent update to address a token generation-related problem that has impacted many users, leading to missed Push Notification deliveries.

**Comment by Anush-Shand** [comment]
@Lakshyasukhralia Could you elaborate on the critical issues in clevertap-android-sdk v6.0.0? If it's unrelated to the above mentioned issue, please open a new issue for ease of tracking.
A workaround has been provided for the above mentioned issue regarding `ClassNotFoundException`.

**Comment by raghavendra-uno** [comment]
Hi @Anush-Shand the issue
Unable to create service com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService: java.lang.ClassNotFoundException: Didn't find class "com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService" on path: DexPathList[[zip file "/data/app/~~pEQX-A6ZftwLCdvutogDFQ==/com.unocoin.unocoinwallet-CEvkvqQEvIJKg6E5hH39aA==/base.apk"],nativeLibraryDirectories=[/data/app/~~pEQX-A6ZftwLCdvutogDFQ==/com.unocoin.unocoinwallet-CEvkvqQEvIJKg6E5hH39aA==/lib/arm64, /data/app/~~pEQX-A6ZftwLCdvutogDFQ==/com.unocoin.unocoinwallet-CEvkvqQEvIJKg6E5hH39aA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64]]

still exists in 6.1.1

**Comment by raghavendra-uno** [comment]
Hi @Anush-Shand  We have updated the app to 6.1.1, but not added
 <service
      android:name="com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService"
      android:exported="false"
      android:enabled="false"
      tools:ignore="MissingClass"/>
still there is spike in Firebase. Should I add the above code in manifest. Adding this is showing a error in manifest of Unresolved class 'CTBackgroundJobService'  is that fine?

**Comment by Anush-Shand** [comment]
@raghavendra-uno 
Yess, the manifest entry needs to be added to prevent the above mentioned crashes. 
Unresolved class shoudn't be an issue as this class in not used in the latest sdk

**Comment by Anush-Shand** [comment]
This issue has been fixed in clevertap-android-sdk v6.2.0

**Comment by andikabrata** [comment]
Is it necessary to add android:name="com.clevertap.android.sdk.pushnotification.amp.CTBackgroundJobService" to the manifest in version 6.2.1 and above?

**Comment by Anush-Shand** [comment]
@andikabrata It is not needed for version 6.2.1 and above
