### ISSUE TITLE
Potential problem with recent firebase instance id sdk

### ISSUE THREAD

**Issue by calvarez-ov** [CleverTap/clevertap-android-sdk#59]
From the firebase instance id release notes:
https://firebase.google.com/support/release-notes/android#iid_v20-1-1

Version 20.1.1 fixes a bug:

> Fixed a bug that was causing silent failures in apps that use the deprecated FirebaseInstanceId#getToken() method without providing the required values for FirebaseOptions: API key, Firebase project ID, and application ID. Now, if any required value is missing, it throws an IllegalArgumentException.
> 
> Note that we recommend using the FirebaseInstanceId.getInstanceId().getToken() method instead of the deprecated FirebaseInstanceId.getInstance().getToken() method.

I noticed that the clevertap sdk is still using the non-recommended, deprecated `FirebaseInstanceId.getInstance().getToken()` method, in `CleverTapAPI.FCMGetFreshToken()`

Please update the sdk to use a more recent version of the firebase dependencies, and to not use deprecated apis.

Apps using the clevertap sdk may be using newer versions of the firebase dependencies, even though cleverap compiles against an old version of messaging, `17.3.0`.

**Comment by darshanclevertap** [comment]
@calvarez-ov Again, sorry for the late reply, I had this noted. This problem is because we currently do not support the latest FCM version because of AndroidX. All that will change once we move to AndroidX by next month, we will fix this in that release as well. Thank you for your patience with us.

**Comment by darshanclevertap** [comment]
@calvarez-ov Sorry for the extreme delay but we have fixed this in the CleverTap Android SDK v4.0.0. This is a major release as we have started supporting AndroidX and the latest FCM dependency so please check out the [changes here](https://github.com/CleverTap/clevertap-android-sdk/blob/master/docs/CTV4CHANGES.md) which we have made before updating.
