### ISSUE TITLE
Custom Notification Builder

### ISSUE THREAD

**Issue by thduc89** [CleverTap/clevertap-android-sdk#65]
Hi CleverTap team, I want to manually control the behavior of my app via PendingIntent when I tap on the notification sent by a Campaign by forming a custom TaskStack, but I can't find any method in your SDK to let me create a raw notification or a NotificationCompat builder (so I can set a PendingIntent myself). So far what I've found is the createNotification method but it fires a notification right away. Please let me know if you had one and if not then will it be there in the future release? I'll really appreciate your help.

**Comment by thduc89** [comment]
please anyone helps me, this is a very critical thing in our project. I just need you to confirm so in the worst case I will find another approach.

**Comment by thduc89** [comment]
@darshanclevertap can you help answer my question, please? Thank you

**Comment by darshanclevertap** [comment]
@thduc89 You can implement your own FirebaseMessagingService and receive the payload from CleverTap. You can then render the notification as you wish. Check out this link for the different keys we send in our Push Notification payload - https://developer.clevertap.com/docs/android#section-custom-android-push-notifications-handling

**Comment by thduc89** [comment]
@darshanclevertap thanks for your reply! I did that already but somehow not satisfied with that way, it's just like I'm reinventing the wheel since your SDK handled rendering the notification very well, only need to customize the behavior when tapping on the notification via PendingIntent. I think I will have to deal with it manually for now. Thank you again!

**Comment by darshanclevertap** [comment]
@thduc89 Could you help me with your use case? You want to customize the pending intent on the click of the notification to achieve what? Most of the app developers want to open their home page or some specific activity, that can be achieved via deep links. If you could explain your use case to me, I'd like to try and help you out.

**Comment by thduc89** [comment]
@darshanclevertap I have several use cases for this, most of them are deeplinks:

1. I tap on a notification, it opens a deeplink page in my app with a custom task stack so when I tap back button it won't open the home page or close my app but `back` to another screen which I put into the custom TaskStackBuilder instead.

2. I tap on a notification, if my app is running and showing the deeplink page which has a TabLayout, it will switch to the specific tab that I put as data in the deeplink URL.

Some other cases I don't remember much by now but the ideas are the same. I handled all of them, everything is going well. 

The only issue left is because I have to customize the TaskStack in PendingIntent manually so I have to follow your above method to extract data from the push notification, put my PendingIntent into it then fire it, so lots of your features like App Icon color, title color, subtitle, big image, actions buttons, etc. are missed. When I said `I will have to deal with it manually for now` I meant I will have to render all these notification UI related things by myself.

Thanks for your concern. I really appreciate it!

**Comment by darshanclevertap** [comment]
@thduc89 Yes, for now, our SDK doesn't solve for such specific use cases. We will take this up internally to see if such use cases are prevalent amongst our user base and try to incorporate them in the SDK in the future.
