### ISSUE TITLE
Crash on InAppNotificationActivity when we try to set a large image

### ISSUE THREAD

**Issue by bhanu-rapido** [CleverTap/clevertap-android-sdk#665]
**Describe the bug**
App is crash with exception "Fatal Exception: java.lang.RuntimeException
Canvas: trying to draw too large(105827460bytes) bitmap."

**To Reproduce**
we are using clevertap android sdk version: 6.1.1

**Expected behavior**
app shouldn't crash, due to this crash our app health degraded very badly, 
Note:  marketing used to setup any banners from clevertap dashboard for inapp notification. 

**Screenshots/Logs**

**Environment (please complete the following information):**
attached a screenshot

**Additional context**

attached the stack trace here
[com.rapido.rider_issue_0ece7b0990753a4805cb2b2f577ff592_crash_session_66E2B6A80393000159CF506CA9DB4B76_DNE_0_v2_stacktrace.txt](https://github.com/user-attachments/files/16977486/com.rapido.rider_issue_0ece7b0990753a4805cb2b2f577ff592_crash_session_66E2B6A80393000159CF506CA9DB4B76_DNE_0_v2_stacktrace.txt)

<img width="587" alt="Screenshot 2024-09-12 at 3 47 31 PM" src="https://github.com/user-attachments/assets/108b9ecd-0c50-4ef2-9797-f428b67706b9">

**Comment by CTLalit** [comment]
@bhanu-rapido I checked the stack trace and it seems it is due to trying to loading a large asset. In stack trace i did not find any logs pertaining to clevertap sdk which might have lead to this crash. Can you provide more details on crash/data to show its rooting from clevertap.

**Comment by bhanu-rapido** [comment]
@CTLalit the firebase crashlytics shows the clevertap activity name. and after stopping the in-app notification, the crash count came to Zero.

do you have compression login on sdk side? or sdk directly render the what ever the image setup in dashboard?

<img width="1270" alt="Screenshot 2024-09-12 at 4 43 53 PM" src="https://github.com/user-attachments/assets/90743d0b-e06d-40b4-a1ed-df5301c0c586">

**Comment by CTLalit** [comment]
Limits are enforced on dashboard and CMS, there is a possibility or media being provided as url (which can be possibly be a large image). We do not provide any compression and it is upon client to upload proper assets and compression might not provide best results and customisation, we do have recommended asset sizes.
In the above crash log the asset size seems ~100MB

Please raise an issue to our support team for this [via this link](https://help.clevertap.com/hc/en-us). We can discuss the campaign which caused the crash and look into it further.

**Comment by CTLalit** [comment]
@bhanu-rapido we do not allow uploading large assets from dashboard/other ui component. Maybe url with large image was used which caused the crash.


CleverTap SDK is not the reason to block app open, the guidelines for android image size are not followed which might be causing the crash.
I would suggest you guys can do phased rollout and even provide that functionality as control group to start things.

We will check if anything can be done to prevent this and if any checks can be added on our side.

Please feel free to open a ticket from above link if you want to discuss further.

**Comment by bhanu-rapido** [comment]
@CTLalit this the image we set from url. image size is less than 2MB.

https://imgur.com/yJ4SlSF

**Comment by CTLalit** [comment]
@bhanu-rapido as per the stack trace posted by you :
`App is crash with exception "Fatal Exception: java.lang.RuntimeException
Canvas: trying to draw too large(105827460bytes) bitmap."`
This is ~100MB image. 

Also a 2MB image should not cause a crash ideally. Maybe you have pointed to wrong campaign and image. If 2MB image loading is causing the crash then you should consider memory footprint of your app and optimise it.

**Comment by bhanu-rapido** [comment]
No. Check the image dimensions

**Comment by bhanu-rapido** [comment]
Before closing the issue, first check in the sample app and then close

**Comment by CTLalit** [comment]
@bhanu-rapido i copied from the stack trace which you have provided in comment. 
You can raise a support ticket further if you want to share campaign from your account which is causing the issue as i mentioned and hence the issue is closed.
