### ISSUE TITLE
onInAppButtonClick not triggering

### ISSUE THREAD

**Issue by Arthur-Tavais-Turbi** [CleverTap/clevertap-android-sdk#67]
Hello.

i'm trying to implement a specific action on the button click of my InAppNotification, but the method onInAppButtonClick is note being called. I've implemented it on my activity, as you can see below:

![image](https://user-images.githubusercontent.com/61332045/79408776-8e61e100-7f72-11ea-8942-c87899b068c6.png)

And i have overrided it as in your documentation:

![image](https://user-images.githubusercontent.com/61332045/79408827-b05b6380-7f72-11ea-8aba-0ae62023d159.png)

The inAppNotification is showing on the app, but clicking on the button don't call the method and only dismiss the notification

Here is the "What" screen of the campaign i'm using to test it:

![image](https://user-images.githubusercontent.com/61332045/79408959-07613880-7f73-11ea-9142-b0f401951f5a.png)

Am i missing somenthing?

**Comment by darshanclevertap** [comment]
@Arthur-Tavais-Turbi Have you set the Listener in your Activity's `onCreate()` like this?
`cleverTapAPI.setInAppNotificationButtonListener(this);`

**Comment by Arthur-Tavais-Turbi** [comment]
That was it! Working like a charm now. Thank You!
