### ISSUE TITLE
FcmTokenListenerService & InAppNotificationActivity in AndroidManifest.xml shows linter error when migrated to AndroidX

### ISSUE THREAD

**Issue by mochadwi** [CleverTap/clevertap-android-sdk#68]
My setup:
```
CleverTap: 3.7.2
Firebase Messaging: 19.0.0
```
please mention me if you need more setup configuration or provide more error/output logs

Linter error:
`Registered class is not instantiatable correctly`
<img width="895" alt="Screen Shot 2020-04-26 at 2 32 04 PM" src="https://user-images.githubusercontent.com/7057959/80300912-b64f1100-87ca-11ea-9d14-370c80b67a87.png">

My Approach:
- This #43 has workaround for the issue with `FcmTokenListenerService` as stated in this [docs](https://developer.clevertap.com/docs/using-fcm-version-1800-and-above)
-  I've also stated my workaround when migrating using `AndroidX` here #38 by manually `jetified` the `clevertap-3.7.2.aar` and add the .aar to the our codebase locally with `flatDirs`
- The above issue won't happened when using `flatDirs` approach, but I've recently remove it and using `jetifier` default approach, seems doesn't works: https://github.com/facebook/facebook-android-sdk/issues/591#issuecomment-619435280
- I don't wanna silence my linter error as warning (this is not a fix) because I need `InAppNotificationActivity` to function correctly

[suggested]
An open function to extends the `InAppNotificationActivity` so we can use correct androidx imports & place it in our `AndroidManifest.xml`

or any workaround/alternative currently to solve this issue? 

P.S: But if the milestone for androidx migration still far away, maybe I just have to add locally the clevertap then T_T

**Comment by darshanclevertap** [comment]
There are two separate issues here - 

1. The `InAppNotificationActivity` is now a part of the CleverTap SDK's `AndroidManifest.xml` and you don't need to add it in your `AndroidManifest.xml` file. That should solve the lint issue.

2. As for the FCMMessageListener class, you can follow #43 and easily avoid any issues.

You don't need to add the AAR file manually if you follow the above 2 steps.

**Comment by mochadwi** [comment]
Now that's great, so it is safe to remove the InAppNotification activity? Did you guys already mentioned this features untuk docs somewhere (the others might not found it too) 

I assume, because AppsFlyer SDK manifest will be merged to our apps manifest (that is safe to remove InAppNotification activity from apps manifest) @darshanclevertap

**Comment by darshanclevertap** [comment]
Yes, @mochadwi CleverTap's manifest gets merged with your app's manifest file at compile time. So you don't need to add it in your manifest separately. I'll check our official documentation as well, and update it if its not. Thanks!
