### ISSUE TITLE
Inbox view in Android 15

### ISSUE THREAD

**Issue by radubn** [CleverTap/clevertap-android-sdk#692]
**Describe the bug**
The toolbar is under the status bar on Android 15.

**To Reproduce**
CT Inbox has been implemented for a while and it's working just fine. However, after setting targetSdk to 35, the inbox is not properly displayed. The toolbar is under the status bar and the back button does not work, only the back gesture.
On the other views in the app, after setting the targetSdk to 35, I had to have the parent CoordinatorLayout with android:fitsSystemWindows="true". 

**Expected behavior**
The Inbox title should be below the status bar and the back button accessible.

**Screenshots/Logs**
```

fun displayCleverTapInbox() {
        cleverTapDefaultInstance?.apply {
            ctNotificationInboxListener = object : CTInboxListener {
                override fun inboxDidInitialize() {
                    this@apply.showAppInbox(
                        CTInboxStyleConfig().apply {
                            navBarTitle = string(R.string.menu_user_inbox)
                            navBarColor = colorAsString(R.color.xxx)
                            navBarTitleColor = colorAsString(R.color.xxx)
                            backButtonColor = colorAsString(R.color.xxx)
                            inboxBackgroundColor = colorAsString(R.color.xxx)
                            noMessageViewText = string(R.string.inbox_default)
                            noMessageViewTextColor = colorAsString(R.color.xxx)
                        }
                    )
                }

                override fun inboxMessagesDidUpdate() {

                }
            }
            initializeInbox()
        }
    }

```

![ct_inbox_android_15](https://github.com/user-attachments/assets/483d4280-2385-4b58-b208-6962647d3e24)

**Environment (please complete the following information):**
 - Device: Google Pixel 6a
 - OS: Android 15
 - CleverTap SDK Version v7.0.2
 - Android Studio Version 2024.2.1 Patch 2 (Ladybug)

**Comment by piyush-kukadiya** [comment]
@radubn We have planned release for Android 15 by end of the December. https://github.com/CleverTap/clevertap-android-sdk/pull/664

**Comment by radubn** [comment]
Thank you!
