### ISSUE TITLE
Dynamic Notification Icon

### ISSUE THREAD

**Issue by theapache64** [CleverTap/clevertap-android-sdk#695]
**Is your feature request related to a problem? Please describe.**  
Yes, the current CleverTap SDK implementation fetches the small notification icon from the `meta-data` tag in the `AndroidManifest`. This metadata is static, meaning it cannot be updated dynamically at runtime or between app launches. This limitation makes it impossible to customize notification icons dynamically.

**Describe the solution you'd like**  
We would like the CleverTap SDK to provide an API to dynamically set or update the small notification icon at runtime. This API should allow overriding the default small notification icon specified in the `AndroidManifest`. This would enable developers to:  
- Update notification icons based on app state or runtime conditions.  
- Customize notification icons dynamically without requiring a new app build or installation.  

**Describe alternatives you've considered**  
- No alternative available

**Comment by CTLalit** [comment]
Dynamic icons are something we do not support as of now, we do have it in the roadmap and up for consideration, we will inform you once we have this support.
