### ISSUE TITLE
Tabs in app inbox

### ISSUE THREAD

**Issue by dduvedi** [CleverTap/clevertap-android-sdk#74]
I have created two tabs for app inbox, but it is showing all as default. Is there a way to remove all?

**Comment by piyush-kukadiya** [comment]
@dduvedi Can you please explain in detail, what issue you are facing?

**Comment by dduvedi** [comment]
i am getting three tabs. whereas i have added only two, the all one is added automatically, is there a way to removed it.

![image](https://user-images.githubusercontent.com/6572193/82429390-6c93d680-9aa9-11ea-8158-a6f1f97be51a.png)

**Comment by piyush-kukadiya** [comment]
@dduvedi There is no way you can remove ALL tab.
ALL tab will be added by default, the other 2 can be configured, every message will be in the ALL tab by default, and depending on the tag you use in the Inbox campaign we will show it in that tab.

**Comment by dduvedi** [comment]
is it possible to change the notification bar colour from black to our theme color?

**Comment by darshanclevertap** [comment]
@dduvedi Yes. See point #3 in our [App Inbox documentation](https://developer.clevertap.com/docs/android#section-app-inbox)

**Comment by dduvedi** [comment]
there is nothing defined as how to change notification bar color

**Comment by darshanclevertap** [comment]
@dduvedi do you mean the status bar? or the Inbox bar where the back button is present?

**Comment by dduvedi** [comment]
status bar/notificatio bar i meant where we signals/ battery etc

**Comment by darshanclevertap** [comment]
@dduvedi Sorry, that cannot be customized

**Comment by dduvedi** [comment]
@darshanclevertap thanks for the quick response. Another thing i want to ask if i will send any push notification it will be available in app inbox?

**Comment by darshanclevertap** [comment]
@dduvedi Yes, we have an option "Send to App Inbox" on our Dashboard when you create a Push Notification Campaign

**Comment by dduvedi** [comment]
@darshanclevertap  same for in-app notification?

**Comment by darshanclevertap** [comment]
@dduvedi No, InApp notifications cannot be sent to App Inbox.

**Comment by dduvedi** [comment]
@darshanclevertap can you tell me apart push notification what else be available in app inbox?

**Comment by darshanclevertap** [comment]
@dduvedi Only Push Notifications 😄

**Comment by dduvedi** [comment]
@darshanclevertap  cool man, thanks alot for your quick support!! :)

**Comment by dduvedi** [comment]
@darshanclevertap in-app notifications aren't allowed in android emulator?
