### ISSUE TITLE
InAppNotificationButtonListener

### ISSUE THREAD

**Issue by dduvedi** [CleverTap/clevertap-android-sdk#75]
I have implemented InAppNotificationButtonListener in my main activity and using clever tap sdk ver 3.8.0 and when i click on button inside in-app notification which was showed in main activity but I am not receiving callback on onInAppButtonClick

**Comment by dduvedi** [comment]
@darshanclevertap can you reply?

**Comment by darshanclevertap** [comment]
@dduvedi `onInAppButtonClick` is called only when there are custom key-value pairs set on that button in the InApp campaign. If you want to know if the InApp was dismissed, implement the `InAppNotificationListener` which has an `onDismissed` callback method

**Comment by dduvedi** [comment]
I have dome the same thing defined custom key value pair on button whereas on click of that ina-pp notification was dismissed and callback was not received on onInAppButtonClick

**Comment by darshanclevertap** [comment]
@dduvedi Have you set the listener like this in your Activity? -

`cleverTapInstance.setInAppNotificationButtonListener(this);`

**Comment by dduvedi** [comment]
Android SDK v3.6.1 and above supports callback on the click of InApp Notification Buttons by returning a Map of Key-Value pairs. To use this, make sure your activity implements the InAppNotificationButtonListener and override the following method : 

@Override
    public void onInAppButtonClick(HashMap<String, String> hashMap) {
        if(hashMap != null){
            //Read the values
        }
    }



No where in the documentation it was defined!

Again thanks for the rescue, you should re-visit your documentation.

**Comment by darshanclevertap** [comment]
@dduvedi Thanks for the suggestion, we will update our documentation

**Comment by dduvedi** [comment]
@darshanclevertap  i was able to receive the callback, thanks for the help.
Though i have a query, we use custom html for templates where we don't create button using standard clever tap campaign creation flow, it there a way to receive callback for that custom template item click?

**Comment by darshanclevertap** [comment]
@dduvedi No there are no callbacks for HTML templates.
