### ISSUE TITLE
Test the Push Amplification!

### ISSUE THREAD

**Issue by Harshit-roid** [CleverTap/clevertap-android-sdk#76]
I have Implemented the push Amplification for Notification in my recent project, then the issue is how to test them, our notification is amplified or not.

**Comment by darshanclevertap** [comment]
@Harshit-roid Sorry for the delay in replying. You can comment out the Firebase Messaging Service from the `AndroidManifest.xml` on a device that doesn't have background limits on processes and you'll be able to receive the push notification from CleverTap via push amplification.
