### ISSUE TITLE
how to test Xiaomi Push Integration.

### ISSUE THREAD

**Issue by gauravtyagi328** [CleverTap/clevertap-android-sdk#77]
I have implement Xiaomi Push notification. but we do not how to to test it.

**Comment by darshanclevertap** [comment]
@gauravtyagi328 When you pass the Xiaomi push token to CleverTap, we show it on your profile page like this - 
![Uploading Screenshot 2020-05-21 at 12.49.42 PM.png…](Xiaomi Push)

You can click on Send Push and the dashboard will give you an option to select which token you want to send it to.

**Comment by darshanclevertap** [comment]
@gauravtyagi328 Hope this solves your issue. Closing this for now. If you still have concerns, feel free to reopen this thread.
