### ISSUE TITLE
refresh token in my Custom FirebaseMessagingService

### ISSUE THREAD

**Issue by darkkillen** [CleverTap/clevertap-android-sdk#78]
I have my custom FirebaseMessagingService and there are "onMessageReceived" and "onNewToken". In "onMessageReceived" I have already implement the notification behavior likes the library but in "onNewToken" I can't call `CleverTapAPI.tokenRefresh(context)`. It's package protected. Any suggestion?

**Comment by darshanclevertap** [comment]
@darkkillen Use the public method `pushFcmRegistrationId("yourToken",true)`
