### ISSUE TITLE
App Inbox

### ISSUE THREAD

**Issue by dduvedi** [CleverTap/clevertap-android-sdk#79]
Can we mark all notification as read after opening app inbox, because right now cleverTapAPIInstance.getInboxMessageUnreadCount() gives count of total notification received.

**Comment by darshanclevertap** [comment]
@dduvedi You can call `markReadInboxMessage(String messageId)` or `markReadInboxMessage(CTInboxMessage message)` in a for loop and mark all the messages as read

**Comment by dduvedi** [comment]
Using which CT method i can get list of all messages and their respective messageId?

**Comment by darshanclevertap** [comment]
@dduvedi the `getAllInboxMessages` returns and `ArrayList` of `CTInboxMessage` class. Read [this documentation here](https://developer.clevertap.com/docs/android#section-creating-your-own-app-inbox) for a better understanding of all our App Inbox methods.

**Comment by darshanclevertap** [comment]
@dduvedi Hope this solves your issue. Closing this now. If you still have concerns regarding this feel free to reopen the issue
