### ISSUE TITLE
I am sending a test notification. In android device it is not visible in notification tray 

### ISSUE THREAD

**Issue by thelocaldev** [CleverTap/clevertap-android-sdk#85]

**Comment by kumaratulismu** [comment]
@utkarshs2099  Can you please tell whether you are getting normal push notification via the dashboard.

Please share the steps for your FCM integration which you have followed.

**Comment by utkarshs2099** [comment]
I'm sending push notification through dashboard, 
and I followed integration of push notification from here https://developer.clevertap.com/docs/android#section-push-notifications

**Comment by kumaratulismu** [comment]
@utkarshs2099 Reach out to support@clevertap.com with your AccountId and detailed explanation of the issue.
They will be able to help out in a better way.

Thanks
Atul
