### ISSUE TITLE
Update documentation about the key parts of notification channel for Android 8+

### ISSUE THREAD

**Issue by sagrawal31** [CleverTap/clevertap-android-sdk#89]
As discussed over the emails & calls, the following 2 points are **VERY MUCH IMPORTANT TO BE MENTIONED IN THE DOCUMENTATION**-

## 1. The developer must create a Notification Channel for Android 8+

The developers must create the [notification channel](https://developer.android.com/training/notify-user/channels) if they want to receive a push notification on Android 8+, otherwise, the notifications will not be rendered.

## 2. The notification channel is by default disabled in debug mode

In debug mode, the notification channel created by default is disabled which needs to be enabled manually by developers. To enable this, they have to go to `App Settings` -> `Notification` -> `Channel Name`.

These two points are very important to save time.

**Comment by darshanclevertap** [comment]
Hi, @sagrawal31 Thank you for the feedback. We have mentioned the creation of Android Notification Channels in our official documentation [here](https://developer.clevertap.com/docs/android#section-push-notifications-for-android-o) We will add the second point as well. 
As you have said this is more important for mobile devs using hybrid frameworks. Hence, closing this here and will keep the [Cordova issue](https://github.com/CleverTap/clevertap-cordova/issues/70) open till we add proper documentation.

**Comment by sagrawal31** [comment]
Got it @darshanclevertap thanks.
