### ISSUE TITLE
ANR's in Dashboard

### ISSUE THREAD

**Issue by singh496** [CleverTap/clevertap-android-sdk#99]
Device, build and operating system infos are same as [this](https://github.com/CleverTap/clevertap-android-sdk/issues/37)
Stacktrace
com.clevertap.android.sdk.ab_testing.CTABTestController" prio=10 tid=28 Native
  | group="main" sCount=1 dsCount=0 obj=0x12c86cf0 self=0xf4b76800
  | sysTid=11154 nice=0 cgrp=default sched=0/0 handle=0xf4a56800
  | state=S schedstat=( 0 0 0 ) utm=0 stm=0 core=2 HZ=100
  | stack=0xde543000-0xde545000 stackSize=1036KB
  | held mutexes=
  #00  pc 000000000003b848  /system/lib/libc.so (__epoll_pwait+20)
  #01  pc 0000000000015721  /system/lib/libc.so (epoll_pwait+26)
  #02  pc 000000000001572f  /system/lib/libc.so (epoll_wait+6)
  #03  pc 00000000000123c3  /system/lib/libutils.so (android::Looper::pollInner(int)+98)
  #04  pc 00000000000125ed  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
  #05  pc 0000000000088359  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
  #06  pc 00000000000b718b  /system/framework/arm/boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+102)
  at android.os.MessageQueue.nativePollOnce (Native method)
  at android.os.MessageQueue.next (MessageQueue.java:143)
  at android.os.Looper.loop (Looper.java:122)
  at android.os.HandlerThread.run (HandlerThread.java:61)

Main thread is waiting, while this is native.

SDK Version: com.clevertap.android:clevertap-android-sdk:3.8.0

**Comment by darshanclevertap** [comment]
@singh496 We shipped a fix for this in our last release. Can you upgrade to v3.9.0 and let us know if the problem persists? I'll keep this thread open for you till then

**Comment by AmitSrivastava89** [comment]
> @singh496 We shipped a fix for this in our last release. Can you upgrade to v3.9.0 and let us know if the problem persists? I'll keep this thread open for you till then

@darshanclevertap 3.9.0 hasn't been officially released and isn't the latest stable version. Is it safe to use a non-stable version for an app which has millions of daily active users on Android?

**Comment by darshanclevertap** [comment]
@AmitSrivastava89 v3.9.0 has been officially released and is stable. It is on our [CHANGELOG](https://github.com/CleverTap/clevertap-android-sdk/blob/master/CHANGELOG.md) and [Releases](https://github.com/CleverTap/clevertap-android-sdk/releases) page as well. I do not know from where did you get the idea its not stable

**Comment by singh496** [comment]
We were referring to [this](https://developer.clevertap.com/docs/changelog)

**Comment by darshanclevertap** [comment]
@singh496 My bad, I'll get the documentation team to update that ASAP.

**Comment by darshanclevertap** [comment]
@singh496 @AmitSrivastava89 We've updated our website documentation as well. Thanks for pointing it out 👍

**Comment by darshanclevertap** [comment]
@singh496 Are you still seeing these ANRs?

**Comment by anjalsaneen** [comment]
Hi @darshanclevertap 

We are still seeing the ANR even after updating to 3.9.0. 


```
  #00  pc 000000000003b748  /system/lib/libc.so (__epoll_pwait+20)
  #00  pc 00000000000151df  /system/lib/libc.so (epoll_pwait+26)
  #00  pc 00000000000151ed  /system/lib/libc.so (epoll_wait+6)
  #00  pc 000000000001280f  /system/lib/libutils.so (android::Looper::pollInner(int)+98)
  #00  pc 0000000000012a39  /system/lib/libutils.so (android::Looper::pollOnce(int, int*, int*, void**)+92)
  #00  pc 0000000000088bcd  /system/lib/libandroid_runtime.so (android::NativeMessageQueue::pollOnce(_JNIEnv*, int)+22)
  #00  pc 00000000000b680b  /system/framework/arm/boot.oat (Java_android_os_MessageQueue_nativePollOnce__JI+102)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:143)
  at android.os.Looper.loop (Looper.java:130)
  at android.app.ActivityThread.main (ActivityThread.java:7007)
  at java.lang.reflect.Method.invoke! (Native method)
  at java.lang.reflect.Method.invoke (Method.java:372)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1404)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:1199)
```
